### ISSUE TITLE
BS皮肤站配合ygg发送cookie报错

### ISSUE THREAD

**Issue by Miuss** [yushijinhun/authlib-injector#101]
![image](https://user-images.githubusercontent.com/26337587/105847872-21d24300-5fd6-11eb-8f1d-989e16440d00.png)

**Comment by yushijinhun** [comment]
反馈 bug 请提供足以复现问题的详细信息：
* 服务端软件以及版本
* 按照的各个插件以及版本
* 添加 `-Dauthlibinjector.debug` 选项开启调试模式，然后提供 **完整** 的控制台日志

你在 QQ 上提到服务器会崩溃，以及你装了「头颅数据库」后才会出现这个问题，因此请你提供：
* 服务器崩溃日志
* 你新安装的插件以及其版本

**Comment by Miuss** [comment]
已找到问题，Matrix反作弊插件问题
