### ISSUE TITLE
[1.16.5-Forge]无法验证玩家用户名

### ISSUE THREAD

**Issue by xslingcn** [yushijinhun/authlib-injector#103]
客户端:Forge-36.0.10,无任何Mod,使用HMCL直接安装（截至提issue时，HMCL中所有源的Forge版本均未同步到36.0.13,但是应该不影响）；
服务端:Forge-36.0.13,无任何Mod；
服务端启动指令:`java -javaagent:authlib-injector-1.1.34.jar=https://littleskin.cn/api/yggdrasil -jar .\forge-1.16.5-36.0.13.jar`
具体表现:客户端使用authlib-injector登录后，在尝试连接Forge服务器时服务端会以`Username 'xsling' tried to join with an invalid session`为由拒绝,客户端提示`无法验证用户名！`
经测试用Vanilla客户端连接Vanilla服务器/Forge客户端连接Vanilla服务器均不会出现以上问题(1.16.5)。
完整客户端log:https://paste.ubuntu.com/p/RWKsYJFvcV/
完整服务端log:https://paste.ubuntu.com/p/6MRbVKbJXX/

**Comment by yushijinhun** [comment]
我无法重现你的问题。麻烦你在服务端和客户端添加 `-Dauthlibinjector.debug` 参数后，再上传一遍日志。

**Comment by Guyao146** [comment]
我刚刚更新1.16.5 同样的问题 也是无法验证玩家用户名

**Comment by yushijinhun** [comment]
@Guyao146 请提供开启 `-Dauthlibinjector.debug` 选项后的日志。

**Comment by Guyao146** [comment]
@yushijinhun 抱歉，刚才去试着抓了下日志，创建了新issues，麻烦看下 https://github.com/yushijinhun/authlib-injector/issues/105

**Comment by yushijinhun** [comment]
@Guyao146 的问题是 authlib-injector 版本过低造成的，和本 issue 不是同一个问题，因此折叠相关 comments。

**Comment by xslingcn** [comment]
加上Debug参数后的完整log:
服务端:https://paste.ubuntu.com/p/fxzcdbpYX9/
客户端:https://paste.ubuntu.com/p/xC6SpDZtct/
(返回了204 No Content？

**Comment by Asnxthaony** [comment]
`server.properties` 文件中 `prevent-proxy-connections` 的值是否为 `false`?

**Comment by xslingcn** [comment]
> `server.properties` 文件中 `prevent-proxy-connections` 的值是否为 `false`?

将`prevent-proxy-connections` 的值更改为 `false`解决了！非常感谢！

**Comment by Wind-Rise** [comment]
草，FRP一类的必须要把代理认证关掉，不然肯定寄

**Comment by YananCoolCD** [comment]
> `server.properties` 文件中 `prevent-proxy-connections` 的值是否为 `false`?
感谢🙇
