### ISSUE TITLE
[1.16.5 Spigot]无法验证用户名

### ISSUE THREAD

**Issue by Guyao146** [yushijinhun/authlib-injector#105]
客户端:HMCL启动 可过HMCL登陆步骤 外部登录使用Blessing Skin 5.2.0  有动态光源 CustomSkinLoader_Fabric-14.13-SNAPSHOT-199皮肤加载 Mod 使用HMCL直接安装
服务端:Spigot 1.16.5 无任何Mod
服务端启动指令:java -Xmx4G -jar -jar -javaagent:authlib-injector-1.1.26-41a7a47.jar=http://pfz.mcylyr.cn/api/yggdrasil 1.16.5.jar nogui 
具体表现:客户端使用authlib-injector登录后，在尝试连接服务器时服务端会以Username 'guyao' tried to join with an invalid session为由拒绝,客户端提示无法验证用户名！
非Debug模式 完整客户端log:https://paste.ubuntu.com/p/MVRPhYDt7c/
非Debug模式 关键部分服务端log:https://paste.ubuntu.com/p/KYt94ndcqz/

我无法重现你的问题。麻烦你在服务端和客户端添加 -Dauthlibinjector.debug 参数后，再上传一遍日志。
添加参数后仍然是显示非Debug模式的日志
服务器端Debug启动参数 java -Xmx4G -jar -jar -javaagent:authlib-injector-1.1.26-41a7a47.jar=http://pfz.mcylyr.cn/api/yggdrasil -Dauthlibinjector.debug 1.16.5.jar nogui 
客户端在HMCL的Minecraft 额外参数处填写Debug参数 log https://paste.ubuntu.com/p/6JM43Zb233/

**Comment by yushijinhun** [comment]
> 客户端在HMCL的Minecraft 额外参数处填写Debug参数

应该在 Java 虚拟机参数处填写 `-Dauthlibinjector.debug`

**Comment by Guyao146** [comment]
> > 客户端在HMCL的Minecraft 额外参数处填写Debug参数
> 
> 应该在 Java 虚拟机参数处填写 `-Dauthlibinjector.debug`。在服务端调试参数需要加在 `-jar` 参数之前。

https://paste.ubuntu.com/p/Y3mtdrcvTk/

**Comment by yushijinhun** [comment]
请不要上传日志文件内容，authlib-injector 的日志是不会输出到日志文件的。请在 HMCL 中使用「测试游戏」功能，然后上传控制台日志。

同时也请上传服务端的控制台日志。

**Comment by Guyao146** [comment]
好的稍等

**Comment by Guyao146** [comment]
客户端：https://paste.ubuntu.com/p/jgXQQWj7Jv/
服务端是这样吗？-Xmx4G -Dauthlibinjector.debug -javaagent:authlib-injector-1.1.26-41a7a47.jar=http://pfz.mcylyr.cn/api/yggdrasil
服务端还是和之前的一样

**Comment by Guyao146** [comment]
客户端：https://paste.ubuntu.com/p/jgXQQWj7Jv/
服务端参数是这样的。但是输出还是那样 java -Xmx4G -Dauthlibinjector.debug -jar -javaagent:authlib-injector-1.1.26-41a7a47.jar=http://pfz.mcylyr.cn/api/yggdrasil 1.16.5.jar nogui

**Comment by yushijinhun** [comment]
你把服务端启动参数换成
```
java -Xmx4G -javaagent:authlib-injector-1.1.26-41a7a47.jar=http://pfz.mcylyr.cn/api/yggdrasil 1.16.5.jar nogui
```
试试？

**Comment by Guyao146** [comment]
稍等

**Comment by Guyao146** [comment]
![image](https://user-images.githubusercontent.com/61780021/106429908-108da880-64a6-11eb-9ece-507ace73c672.png)

**Comment by yushijinhun** [comment]
> ![image](https://user-images.githubusercontent.com/61780021/106429908-108da880-64a6-11eb-9ece-507ace73c672.png)

抱歉，我漏了个 `-jar`。麻烦你再试一下：
```
java -Xmx4G -Dauthlibinjector.debug -javaagent:authlib-injector-1.1.26-41a7a47.jar=http://pfz.mcylyr.cn/api/yggdrasil -jar 1.16.5.jar nogui
```

**Comment by Guyao146** [comment]
ok没事的，稍等

**Comment by Guyao146** [comment]
服务端关键部分 https://paste.ubuntu.com/p/BQX2V3XyjP/
服务端完整 https://paste.ubuntu.com/p/8XWrSj3zd7/

**Comment by yushijinhun** [comment]
请把 authlib-injector 升级到最新版 1.1.34。

**Comment by Guyao146** [comment]
稍等，我试下

**Comment by Guyao146** [comment]
> 请把 authlib-injector 升级到最新版 1.1.34。

感谢，问题已解决
