### ISSUE TITLE
1.1.34这个版本对21w05b没有作用。

### ISSUE THREAD

**Issue by cybmp3** [yushijinhun/authlib-injector#106]
1.1.34这个版本对21w05b没有作用。
[latest.log](https://github.com/yushijinhun/authlib-injector/files/5936914/latest.log)

**Comment by yushijinhun** [comment]
我测试了 21w05b，完全正常。

请问你是如何加载 authlib-injector？麻烦提供一下启动命令行。

**Comment by cybmp3** [comment]
是我自己的问题。谢谢
