### ISSUE TITLE
Ely.by custom authserver

### ISSUE THREAD

**Issue by Carlosjrlu** [yushijinhun/authlib-injector#107]
Is it possible to manually set the auth server with this:

**Auth:**
- https://authserver.ely.by/auth/authenticate
- https://authserver.ely.by/auth/refresh
- https://authserver.ely.by/auth/validate
- https://authserver.ely.by/auth/signout
- https://authserver.ely.by/auth/invalidate

**Session server:**
- https://authserver.ely.by/session/join
- https://authserver.ely.by/session/hasJoined
- https://authserver.ely.by/session/profile/{uuid}

Ely.by don't seem to have integrated the Yggdrasil API, I just want to authenticate through their server.

**Comment by yushijinhun** [comment]
I've just deployed an authentication service [elyby.yushi.moe](https://elyby.yushi.moe/), which forwards requests to Ely.by's server.

Here is the source: https://gist.github.com/yushijinhun/6e96e6d336144deb6a68e762f2597a23

**Comment by Carlosjrlu** [comment]
It works!! Thank you man! I really appreciate it.

**Comment by Carlosjrlu** [comment]
Btw, is there anyway I can get head renders from their skin server?

**Comment by Carlosjrlu** [comment]
For anyone looking for an answer to my last question
https://ely.by/services/skins-renderer?url=http://skinsystem.ely.by/skins/Notch.png&scale=18.9&renderFace=1
