### ISSUE TITLE
开启了SSL然后无法打开

### ISSUE THREAD

**Issue by xiaobailoves** [yushijinhun/authlib-injector#111]
![image](https://user-images.githubusercontent.com/71917424/110625624-9ce46700-81da-11eb-8756-a6783d084d21.png)
请问要怎么修复,关闭SSL吗？

**Comment by tnqzh123** [comment]
验证服务器使用的证书的证书链不全，补全即可

**Comment by xiaobailoves** [comment]
请问怎么补全，没接触过后端不懂感谢

**Comment by tnqzh123** [comment]
几个主流的 Let's Encrypt 证书申请工具都会直接输出全链证书，直接用那个就行了

**Comment by xiaobailoves** [comment]
我用FreeSSL可以吧[狗头]

**Comment by xiaobailoves** [comment]
> 几个主流的 Let's Encrypt 证书申请工具都会直接输出全链证书，直接用那个就行了
![image](https://user-images.githubusercontent.com/71917424/110628633-395c3880-81de-11eb-9d43-0d25a4da72c3.png)
换了SSL还是那个样

**Comment by Kiritow** [comment]
有没有可能是用容器开的，然后没装证书[挠头]

**Comment by yushijinhun** [comment]
原因一般都是 TLS 证书链不全，但也有可能是客户端 Java 不信任证书的颁发 CA（Java 8u101 前的版本不信任 IdenTrust CA，用不了 Let's Encrypt）。
