### ISSUE TITLE
使用皮肤站的Yggdrasil API后hmcl启动器无法登陆

### ISSUE THREAD

**Issue by djkcyl** [yushijinhun/authlib-injector#112]
https://paste.ubuntu.com/p/bFp2hFRVHM/
![image](https://user-images.githubusercontent.com/59153990/113165471-83cc5480-9274-11eb-9c70-5d7a745ebc77.png)

**Comment by yushijinhun** [comment]
字面意思。日志中报错是因为服务器返回的响应不是 JSON 格式。

**Comment by djkcyl** [comment]
> 字面意思。日志中报错是因为服务器返回的响应不是 JSON 格式。

那这个要怎么解决呢，是用的皮肤站的插件市场里安装的 Yggdrasil API 插件
直接访问 https://skin.xxxxxxx.xx/api/yggdrasil 是没问题的

**Comment by yushijinhun** [comment]
你可以换新版本 HMCL  试一下，然后再传一下日志。HMCL 3.3.183 会在日志里输出服务端响应的内容，可以看到服务端到底返回了什么。

**Comment by djkcyl** [comment]
> 你可以换新版本 HMCL 试一下，然后再传一下日志。HMCL 3.3.183 会在日志里输出服务端响应的内容，可以看到服务端到底返回了什么。

https://paste.ubuntu.com/p/NbXDpNqkPd/
这里是hmcl的日志

**Comment by yushijinhun** [comment]
是 BS 报错了，内容是：
```
Details: Argument 1 passed to Lcobucci\JWT\Signer\Key\InMemory::plainText() must be of the type string, null given, called in /usr/local/lighthouse/softwares/btpanel/wwwroot/skin.cyllive.cn/plugins/yggdrasil-api/src/Controllers/AuthController.php on line 37
```
你尝试升级一下 BS 和 BS 插件，如果问题依然存在，请联系 BS 的开发者。

**Comment by Asnxthaony** [comment]
请在 Blessing Skin 根目录下（不是 Web 根目录）下执行以下命令：

`php artisan jwt:secret --show`

并编辑 `.env` 文件，在行尾追加一行 `JWT_SECRET={执行上面命令得到的结果}`
