### ISSUE TITLE
服务端无法连接到验证服务器

### ISSUE THREAD

**Issue by MrSnake0208** [yushijinhun/authlib-injector#113]
![image](https://user-images.githubusercontent.com/74225450/115140232-d9707180-a068-11eb-903f-9c5b79cfa731.png)
启动参数如下：
java -javaagent:authlib-injector.jar=http://s3.skyecs.com:13304/api/yggdrasil -Xms10G -Xmx10G -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true -jar server.jar nogui

**Comment by yushijinhun** [comment]
字面意思，验证服务器拒绝链接。

不过我测试了一下，从我这里是可以访问 s3.skyecs.com:13304 的。建议检查下网络配置是否正常。

**Comment by MrSnake0208** [comment]
> 字面意思，验证服务器拒绝链接。
> 
> 不过我测试了一下，从我这里是可以访问 s3.skyecs.com:13304 的。建议检查下网络配置是否正常。

对，我的各个也可以访问，但是就是不知道为什么在服务端启动的时候，它会这样显示，服务器上网络配置一切正常，就是有过梯子，会是这个的原因嘛

**Comment by yushijinhun** [comment]
那你关掉梯子能正常连接吗？

**Comment by MrSnake0208** [comment]
> 那你关掉梯子能正常连接吗？

也还是不行，依旧是这个问题

**Comment by yushijinhun** [comment]
可以检查下域名解析结果是否正确，有没有出站防火墙之类。

这个问题和 authlib-injector 并没有关系，所以我这边也帮不了什么。
