### ISSUE TITLE
控制台大量出现"Failed to transform"警告

### ISSUE THREAD

**Issue by lwh9346** [yushijinhun/authlib-injector#114]
环境：
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
服务端程序：快照21w19a官方端
authlib-injector版本：1.1.34

错误内容：
[authlib-injector] [WARNING] Failed to transform [{这里每句都不一样，详见日志}]

启动参数：
../jdk/bin/java.exe -jar -javaagent:./authlib-injector.jar=https://mc.whl.red/api/yggdrasil -Dauthlibinjector.debug=verbose,authlib,dumpClass,printUntransformed server.jar nogui

我在程序运行目录下没有发现authlib-injector.log，不知道为啥，所以我手动复制了一部分控制台输出

[bug_report.zip](https://github.com/yushijinhun/authlib-injector/files/6472511/bug_report.zip)

**Comment by yushijinhun** [comment]
这是因为 authlib-injector 使用的 ASM 版本过低造成的，21w19a 使用了 Java 16。
