### ISSUE TITLE
[功能请求]静态转换服务器 jar

### ISSUE THREAD

**Issue by Glavo** [yushijinhun/authlib-injector#116]
目前 authlib-injector 使用 javaagent 机制运行时转换字节码实现外置登录功能，这种实现方式对于生成 native-image 很不友好，所以是否可以考虑一下提供静态修改服务端 authlib 的功能？

具体大概就是是使用类似这样的命令
```
java -jar authlib-injector-.xx.jar -u https://littlesk.in/api/yggdrasil -i minecraft_server.jar -o new_minecraft_server.jar
```
生成一个新的 `new_minecraft_server.jar` 服务端 jar，该 jar 的 authlib 已被修改，并且必要的额外依赖都已经生成在内，可以直接使用 `java -jar new_minecraft_server.jar` 执行，使用静态转换时传入的服务端地址进行身份验证验证。

**Comment by yushijinhun** [comment]
要实现该功能 authlib-injector 需要做出较大的改动，日后可能会考虑。
