### ISSUE TITLE
Reverse proxy error: SSLHandshakeException

### ISSUE THREAD

**Issue by WindLeaf233** [yushijinhun/authlib-injector#119]
## 问题描述

使用 authlib-injector 启动后, 无法进入使用 yggdrisil api 验证的服务器. 检查日志后, 在 `authlib-injector.log` 中发现了如下错误:

```
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed:
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

## 日志

[完整日志](https://paste.ubuntu.com/p/M2MXMwb8w2/)

## 版本

- 客户端 authlib-injector 版本: 使用 HMCL 自动下载的最新版 (1.1.35)
- 服务端 authlib-injector 版本: 1.1.34

我猜这并不是版本不同引起的

**Comment by yushijinhun** [comment]
可能是你验证服务器 TLS 证书无效或证书链不全，或者客户端 Java 版本低于 8u101。

详细回答参考：https://github.com/yushijinhun/authlib-injector/pull/117#issuecomment-841990531
