### ISSUE TITLE
custom service

### ISSUE THREAD

**Issue by EvilToasterDBU** [yushijinhun/authlib-injector#131]
I tried to make a proxy for the [minesocial.net](https://minesocial.net) system based on [this developments](https://github.com/yushijinhun/elyby-proxy), the result is:
`[authlib-injector] [ERROR] Unrecognized proxy URL: minesocial.eviltoaster.workers.dev`
Run command: `-javaagent:authlib-injector.jar -Dauthlibinjector.mojangProxy=minesocial.eviltoaster.workers.dev -jar mohist.jar`
Help me please.

**Comment by EvilToasterDBU** [comment]
I i use `-javaagent:authlib-injector.jar=minesocial.eviltoaster.workers.dev -jar mohist.jar`
result `
[authlib-injector] [INFO] Authentication server: https://minesocial.eviltoaster.workers.dev
[authlib-injector] [ERROR] Failed to fetch metadata: java.io.IOException: Server returned HTTP response code: 403 for URL: https://minesocial.eviltoaster.workers.dev
`

**Comment by yushijinhun** [comment]
I tested your authentication service and it seems to work fine:
```
$ java -javaagent:authlib-injector-1.1.38.jar=minesocial.eviltoaster.workers.dev -version
[authlib-injector] [INFO] Logging file: /home/yushi/authlib-injector.log
[authlib-injector] [INFO] Version: 1.1.38
[authlib-injector] [INFO] Authentication server: https://minesocial.eviltoaster.workers.dev
[authlib-injector] [INFO] Disabled Mojang namespace
[authlib-injector] [INFO] Polyfill privileges API
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

If you're still experiencing this problem, try turning off Cloudflare's Browser Integrity Check (in Firewall / Settings).

**Comment by EvilToasterDBU** [comment]
thanks, i add free domain to cloudflare and edit settings + add worker to http://minesocial.evltstrdbu.tk/ and all works

**Comment by EvilToasterDBU** [comment]
I'm at work now, so I can't check it properly.  Try using the injector with the address http://minesocial.evltstrdbu.tk/ when loading server, I see that there is an authentication request at the address http://minesocial.evltstrdbu.tk/authenticate and not https://authserver.minesocial.net/authenticate, and other request addresses.

**Comment by EvilToasterDBU** [comment]
I solved the problem by creating page redirection rules in cloudflare 

```
minesocial.ml/sessionserver/* -> https://sessionserver.minesocial.net/$1
minesocial.ml/api/*-> https://api.minesocial.net/$1
minesocial.ml/authserver/*-> https://authserver.minesocial.net/$1
```
And all good works.

![Снимок экрана (72)](https://user-images.githubusercontent.com/15957247/125179008-867f0400-e1ea-11eb-97c0-242e27228157.png)

But there was a problem with the display of the cape of another player

![image](https://user-images.githubusercontent.com/15957247/125179025-b3331b80-e1ea-11eb-9624-040b9f1950cc.png)

So far, I am solving this problem from the client side by disabling the cape in the skin customization, but I am curious to know how to solve this problem correctly.

**Comment by yushijinhun** [comment]
The best way is to let minesocial.ml implement authlib-injector's API, so that there is no need to use [elyby-proxy](https://github.com/yushijinhun/elyby-proxy) as an API adapter.
