### ISSUE TITLE
【功能请求】希望能支持一下geyser的登陆

### ISSUE THREAD

**Issue by luluxiaoyu** [yushijinhun/authlib-injector#132]
希望能支持在基岩版通过geyser代理进行登录，即在基岩版中选mojang账户登陆时 希望可以调用皮肤站进行登录

**Comment by yushijinhun** [comment]
我对 Geyser 不是很熟，但 authlib-injector 应该是支持 Geyser 的，因为之前有人反馈过问题，并且也修复了，见 #83。

**Comment by yushijinhun** [comment]
authlib-injector 是支持 Geyser 的，在服务端加载 authlib-injector 即可。Bedrock Edition 登录时需选择「使用 Mojang 账户登录」，然后使用皮肤站账户登录。

**Comment by luluxiaoyu** [comment]
输入完账号密码卡在了虚空呀

**Comment by yushijinhun** [comment]
> 输入完账号密码卡在了虚空呀

请尝试更新到最新的 authlib-injector v1.1.39。我测试了 Geyser 插件，一切正常。

**Comment by Sakuraiina** [comment]
玩家进入的第一次可以登录，并且正常运行，在玩家退出后重新尝试登入的时候，选择mojang登录不会弹出密码 而且会直接卡在虚空（iOS apple store下载的客户端）。我使用了bc，在第一次登录并输入完密码和用户名的时候authlib会在后台：
16:18:32 [信息] [Geyser-BungeeCord] /ip地址:端口 尝试连接!
>[authlib-injector] [INFO] Transformed [com.github.steveice10.mc.auth.service.MsaAuthenticationService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.github.steveice10.mc.auth.service.MojangAuthenticationService] with [Constant URL Transformer]
16:18:33 [信息] [Geyser-BungeeCord] 玩家以 玩家ID 的用户名建立了连接
>[authlib-injector] [INFO] Transformed [com.github.steveice10.mc.auth.service.SessionService] with [Constant URL Transformer]
16:19:00 [信息] [Geyser-BungeeCord] Sakuraiina (登录为: 玩家ID) 已连接到 Java 服务器
16:19:00 [信息] [/ip地址:端口] <-> InitialHandler has connected
[authlib-injector] [INFO] Transformed [net.md_5.bungee.util.AllowedCharacters] with [BungeeCord Allowed Characters Transformer]
16:19:00 [信息] [Sakurai_Kana] <-> ServerConnector [服务器名称] has connected
16:19:01 [信息] Netty is not using direct IO buffers.

第二次登入为：
16:20:59 [信息] [Geyser-BungeeCord] /127.0.0.1:60516 尝试连接!
16:20:59 [信息] [Geyser-BungeeCord] 玩家以 Sakuraiina 的用户名建立了连接

我的能力有限 无法判断是什么问题 但由于重启bc后又可以再次重复这个过程 所以我猜测是缓存等问题造成的？
希望能解决 谢谢
