### ISSUE TITLE
进入服务器提示「无效会话」

### ISSUE THREAD

**Issue by Mashirl** [yushijinhun/authlib-injector#133]
[日志](https://pastebin.ubuntu.com/p/ZbcqGnQvbQ/)

**Comment by yushijinhun** [comment]
可能是登录过期了，请尝试重新登录。

**Comment by Mashirl** [comment]
> 
> 
> 可能是登录过期了，请尝试重新登录。

重新登录试过了，不行。这次是在本地开了个Paper 1.17.1的服务端试的。

客户端日志：https://pastebin.ubuntu.com/p/ShBWqKQqmq/
服务端日志：https://pastebin.ubuntu.com/p/9qN6f6VyPb/

**Comment by Mashirl** [comment]
或许是LittleSkin的问题，我用另一个LittleSkin账号就可以正常登录。

**Comment by yushijinhun** [comment]
@Mashirl 帮你看过了，你 LittleSkin 上账户的邮箱未验证。

**Comment by Mashirl** [comment]
> @Mashirl 帮你看过了，你 LittleSkin 上账户的邮箱未验证。

似乎是邮箱大小写的问题，我这是很久之前就注册的号了，不会未验证，未验证应该正好是当时改邮箱的时候（

谢谢dalao（
