### ISSUE TITLE
Auht Server

### ISSUE THREAD

**Issue by Dev4lexG** [yushijinhun/authlib-injector#142]
How i can create a Auht Server?
youtube tutorials?
wiki tutorial?
...

**Comment by August7** [comment]
> How i can create a Auht Server? youtube tutorials? wiki tutorial? ...

https://github.com/prinsss/blessing-skin-server

**Comment by Big-Cake-jpg** [comment]
> > How i can create a Auht Server? youtube tutorials? wiki tutorial? ...
> 
> 
> 
> https://github.com/prinsss/blessing-skin-server

Outdated, you should let him/her see https://github.com/bs-community/blessing-skin-server

**Comment by Dev4lexG** [comment]
anyone can recommend me one auth server? (not skin server)
