### ISSUE TITLE
如何实现使用authlib-injector加载多个yggdrasil

### ISSUE THREAD

**Issue by Cinnamoroll-cat** [yushijinhun/authlib-injector#146]
我有一个服务器，我需要使用两个皮肤站进行登录，分别为： [https://littleskin.cn/api/yggdrasil] 和[https://mcskin.snowflake.moe/api/yggdrasil] ，便于我更统一的管理服务器，由于有些皮肤站可能不稳定，所以也提供了使用备用站，请问这应该怎么搞？

**Comment by Cinnamoroll-cat** [comment]
我需要首先使用 [https://mcskin.snowflake.moe/api/yggdrasil] 进行登录，同时可以使用 [https://littleskin.cn/api/yggdrasil] 和正版启动器进行登录，而不是只有一个皮肤站。

**Comment by yushijinhun** [comment]
authlib-injector 只支持使用一个验证服务器。
