### ISSUE TITLE
NachoSpigot上玩家无法进入

### ISSUE THREAD

**Issue by HowardZHY** [yushijinhun/authlib-injector#147]
![image](https://user-images.githubusercontent.com/96782166/154828319-bb48b5e5-7f25-4e44-bbd1-8600feb947ed.png)
![%V KMDUE1MBL~$9U~FD3{$Y](https://user-images.githubusercontent.com/96782166/154828375-b6c46896-c25c-41ae-bc21-3d2c7a8557be.png)
1.8.8服务端,1.8.9客户端badpacket奇怪的数值(几万到负数都有),1.8客户端见图,服务端只有disconnect
Logging started at 2022-02-20T04:17:57.739Z
[authlib-injector] [INFO] Version: 1.1.39
[authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
[authlib-injector] [INFO] Polyfill privileges API
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Callback Metafactory Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Class File Version Transformer]
[authlib-injector] [INFO] Httpd is running on port 64497
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Yggdrasil Public Key Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Callback Metafactory Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Class File Version Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.citizensnpcs.Settings$Setting] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.citizensnpcs.Settings$Setting] with [Citizens2 Support]
客户端服务端log均无报错
usercache.json没有玩家进入信息

**Comment by HowardZHY** [comment]
![image](https://user-images.githubusercontent.com/96782166/154828488-10719bdd-ed98-4eee-a9e6-0159fede2c8a.png)

**Comment by HowardZHY** [comment]
在最新的版本依然存在

**Comment by HowardZHY** [comment]
![image](https://user-images.githubusercontent.com/96782166/154830340-0c740fd2-0e1b-4e02-9aca-eb32db39db6c.png)

**Comment by yushijinhun** [comment]
使用 authlib-injector v1.1.42 和 NachoSpigot (https://github.com/CobbleSword/NachoSpigot/commit/74ed0ea729bdf19a4ba0329524b31669fdfea2a4) 无法复现，Java 版本 openjdk 17.0.2。

**Comment by HowardZHY** [comment]
我是jdk8u311.我猜测CobbleSword/NachoSpigot/commit/0a3a65e27711c877ad90808f04d0a5d161058cdc修复了这个,但我没时间确认



在 2022-04-03 18:41:14，"Haowei Wen" ***@***.***> 写道：

使用 authlib-injector v1.1.42 和 NachoSpigot ***@***.***) 无法复现，Java 版本 openjdk 17.0.2。

**Comment by HowardZHY** [comment]
NachoSpigot was ended. WindSpigot is not tested.



在 2022-06-26 05:00:18，"Haowei Wen" ***@***.***> 写道：

Closed #147 as not planned.
