### ISSUE TITLE
披风加载问题

### ISSUE THREAD

**Issue by Ritenseki** [yushijinhun/authlib-injector#153]
使用Authlib-injector和Blessing Skin的Yggdrasil API配置，每次都不能正常加载皮肤站披风；
在NameMC上查询发现有同名的正版用户，游戏中加载的为该正版用户的披风。
请问这种问题现在暂时无法避免么？

**Comment by yushijinhun** [comment]
请检查你是否安装了CustomSkinLoader模组。
