### ISSUE TITLE
Crash on startup with authlib-injector-1.1.44.jar

### ISSUE THREAD

**Issue by Pkyd** [yushijinhun/authlib-injector#160]
Cannot start instance with Authlib-injector-1.1.44, seem like Window Defender detected the JAR file as Trojan:Script/Wacatac.B!ml and block launcher from open the file

**Comment by yushijinhun** [comment]
I've scanned `authlib-injector-1.1.44.jar` with Microsoft Defender and [VirusTotal](https://www.virustotal.com/gui/file/9bfc5299b93c44df8dcff7d88051f78d4142b5ac3f3cbdba80878e3b52b2a526). No threat is found.

**Comment by Lama3L9R** [comment]
Maybe your JVM is infected. Check your JVM executable hashes. If everything is ok then just disable windows defender or add to whitelist.
