### ISSUE TITLE
服务器启用外置登录验证后，皮肤无法加载

### ISSUE THREAD

**Issue by luluxiaoyu** [yushijinhun/authlib-injector#161]
服务器启用外置登录验证后，皮肤无法加载（别人看不见，自己看的见）  
**环境：**  
服务端：1.19RC1-官方server  
littleskin：6 rc2  
authlib：客户端，服务端均为1.1.44  

具体表现：自己可以看到自己的皮肤站上的皮肤，别人看就是steve/alex  
服务端onlinemode是true

**Comment by yushijinhun** [comment]
22w19a 起 Minecraft 使用的 authlib 版本为 22w19a，目前 authlib-injector 还没有支持 authlib v3.5.41。
