### ISSUE TITLE
获取皮肤所使用的端口号如何修改？

### ISSUE THREAD

**Issue by zsn741656478** [yushijinhun/authlib-injector#166]
用的PCL启动器，但一直无法获取头像，报错里显示使用的地址端口是以前用的。尝试在站点配置里修改站点地址后，点击提交，依旧没有任何改变。该如何修改地址？

**Comment by yushijinhun** [comment]
这个问题和 authlib-injector 项目本身无关，建议联系 PCL 作者解决。

**Comment by zsn741656478** [comment]
> 这个问题和 authlib-injector 项目本身无关，建议联系 PCL 作者解决。

启动器获取皮肤地址应该是皮肤站提供的，有无可能是皮肤站提供了错误地址给启动器？

**Comment by yushijinhun** [comment]
你可以测试下其他启动器（如 HMCL）是否有这个问题。如果也有，说明应该是皮肤站的问题；如果没有，说明是 PCL 的问题。
