### ISSUE TITLE
Found a violation of the license

### ISSUE THREAD

**Issue by qwq233** [yushijinhun/authlib-injector#168]
在对[HMCL PE](https://github.com/Tungstend/HMCL-PE)反编译的过程中 发现了疑似authlib injector的包名
![image](https://user-images.githubusercontent.com/20317838/177008279-49aef8eb-4682-401f-bc12-6c4af73dc1d7.png)
该软件虽为GPL许可证 但提供了非开源且收费的"内测版本"
且包含有[缺失便无法编译的组件](https://github.com/Tungstend/HMCL-PE/pull/27#issuecomment-1166523147)

我本人先前通过邮件询问过Free Software Foundation的人员，非原始代码提供者在这种"缺失关键组件"的项目引用/使用AGPL协议授权的代码属于违反AGPL的行为。

本人建议向GitHub Staff提交[DMCA 删除申请](https://docs.github.com/en/site-policy/content-removal-policies/guide-to-submitting-a-dmca-takedown-notice)，若不方便，授权本人也可。

![image](https://user-images.githubusercontent.com/20317838/177008706-a0a0c39d-99c7-4cda-a24d-cef3a582941a.png)

**Comment by Tungstend** [comment]
别搞错了，所有功能都开源，内测也开源，只有验证体系没开源罢了，我们又没禁止你修改，你完全可以把验证部分扬了，和内测一模一样，authlib只是扔了一个jar进去

**Comment by qwq233** [comment]
> 别搞错了，所有功能都开源，内测也开源，只有验证体系没开源罢了，我们又没禁止你修改，你完全可以把验证部分扬了，和内测一模一样，authlib只是扔了一个jar进去

首先 我不是违反协议方 我没有责任为你的过错负责

其次 你说authlib只是扔了一个jar进去 那么请你移除

最后 因为你向我提供了你添加的"内测"版本 我发现该内测版与你提供源文件不符 再加之你已经在你所提供的版本已经含有非你发布的内容/源代码/编译产物/附属资源 根据GPLv3协议第六款有关以非源码形式转发的有关规定 向你索求该部分源码 若你不提供 则视为违反GPL的行为

**Comment by qwq233** [comment]
> 

还有 有没有可能 你违反了所有你引用的非著作权人不是你的GPL项目的协议

**Comment by Tungstend** [comment]
随便你怎么想，我也没说过我要严格遵守gpl，我只在我认为合理的范围内鼓励用户赞助，毕竟如果用户实在不想赞助，他只需要对源码稍作修改即可破解，我们并不禁止这种行为，大多数人也并不反对我们这么做，你或者任何人如果有意见，那也和我没关系，我也不会因为你做什么修改，至多删库跑路都别玩，我们也并不在乎收的赞助费，只不过有比没有好罢了。

**Comment by yushijinhun** [comment]
HMCLPE 确实使用到了 authlib-injector 项目，但 HMCLPE 是通过 javaagent 方式将 authlib-injector 加载进游戏，其本身并未与 authlib-injector 进行 linking，因此不会被 authlib-injector 传染 AGPLv3，没有存在违反 authlib-injector 许可的情况。

**Comment by qwq233** [comment]
@yushijinhun 不 他所提供的apk包的asset包含了authlib-injector的资源 我认为这已经算是被传染了 我认为如果要规避感染 正确的做法应该是不在apk包提供 需要时在网络下载

**Comment by yushijinhun** [comment]
> @yushijinhun 不 他所提供的apk包的asset包含了authlib-injector的资源 我认为这已经算是被传染了 我认为如果要规避感染 正确的做法应该是不在apk包提供 需要时在网络下载

对于你所说的情况，我已经修改了 authlib-injector 的许可，添加了例外条款避免这种情况下启动器被传染。
