### ISSUE TITLE
身份认证目前正在停机维护

### ISSUE THREAD

**Issue by HoratioShaw** [yushijinhun/authlib-injector#173]
客户端Java版本为8.0.3410.10 服务端版本为openjdk version "1.8.0_312" ，使用blessing-skin-server配合yggdrasil api，证书尝试了let's encrypt和TrustAsia RSA DV TLS CA G2，连接服务器时均会显示身份认证目前正在停机维护，启动参数：java -javaagent:skin.jar=https://xxxxxx/api/yggdrasil -jar start.jar/（链接已替换，并且能正常访问附加-Dnetworkaddress.cache.ttl=0 也试了）
服务器已打开正版验证
连接以后会提示com.mojang.authlib.GameProfile@2555eca8[id=<null>,name=Horatio,properties={},legacy=false] (/111.85.58.85:46367) lost connection: Disconnected

客户端日志：
Logging started at 2022-08-04T21:48:13.636Z
[authlib-injector] [INFO] Version: 1.1.47
[authlib-injector] [INFO] Authentication server: https://xxxxxx/api/yggdrasil
[authlib-injector] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector] [INFO] Enable MC-52974 Workaround
[authlib-injector] [INFO] Enable MC-52974 Workaround for 1.7.10
[authlib-injector] [INFO] Httpd is running on port 63114
[authlib-injector] [INFO] Transformed [net.minecraft.client.entity.AbstractClientPlayer] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.util.Session] with [1.7.10 MC-52974 Workaround (Session)]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Yggdrasil Public Key Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [MC-52974 Workaround]
[authlib-injector] [INFO] Transformed [customskinloader.loader.MojangAPILoader] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [net.minecraft.network.play.server.S0CPacketSpawnPlayer] with [1.7.10 MC-52974 Workaround (S0CPacketSpawnPlayer)]
[authlib-injector] [INFO] Transformed [io.netty.bootstrap.Bootstrap] with [Constant URL Transformer]
[authlib-injector] [WARNING] Reverse proxy error
java.net.ConnectException: Connection refused: connect
	at java.net.TwoStacksPlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
	at sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
	at sun.net.NetworkClient.doConnect(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.http.HttpClient.openServer(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.<init>(Unknown Source)
	at sun.net.www.protocol.https.HttpsClient.New(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$6.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(Unknown Source)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.access$100(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection$8.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessController.doPrivilegedWithCombiner(Unknown Source)
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(Unknown Source)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at moe.yushi.authlibinjector.httpd.URLProcessor.reverseProxy(URLProcessor.java:192)
	at moe.yushi.authlibinjector.httpd.URLProcessor.access$400(URLProcessor.java:47)
	at moe.yushi.authlibinjector.httpd.URLProcessor$1.serve(URLProcessor.java:158)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.HTTPSession.execute(HTTPSession.java:246)
	at moe.yushi.authlibinjector.internal.fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:104)
	at java.lang.Thread.run(Unknown Source)

服务端：
Logging started at 2022-08-04T21:20:11.886Z
[authlib-injector] [INFO] Version: 1.2.0
[authlib-injector] [INFO] Authentication server: https://xxxx/api/yggdrasil
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[authlib-injector] [INFO] Httpd is running on port 45169
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Constant URL Transformer]

**Comment by Big-Cake-jpg** [comment]
请服务端和客户端都使用 1.2.0 版本的 authlib-injector 并检查客户端网络

**Comment by HoratioShaw** [comment]
> 请服务端和客户端都使用 1.2.0 版本的 authlib-injector 并检查客户端网络

用的都是1.2.0，客户端网络也能连上api

**Comment by yushijinhun** [comment]
请在服务端添加 -Dauthlibinjector.debug 参数，然后再上传日志。

**Comment by HoratioShaw** [comment]
> 请在服务端添加 -Dauthlibinjector.debug 参数，然后再上传日志。

Logging started at 2022-08-05T22:35:51.514Z
[authlib-injector] [INFO] Version: 1.2.0
[authlib-injector] [INFO] Authentication server: https://skin.443.fyi/api/yggdrasil
[authlib-injector] [DEBUG] Metadata: {"meta":{"serverName":"\u552f\u87f9\u76ae\u80a4\u7ad9","implementationName":"Yggdrasil API for Blessing Skin","implementationVersion":"5.1.5","links":{"homepage":"https:\/\/skin.443.fyi","register":"https:\/\/skin.443.fyi\/auth\/register"},"feature.non_email_login":true},"skinDomains":["skin.443.fyi"],"signaturePublickey":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAwudS82wiAjdcc8vKzru6\nkroVsScjJMENdtVhiAM8lX14k1Y3zDLwilnwCSYg8XaqzWHcunikVrNTuM0caEKp\nAhAsBRoiLbJk76QUdS2kXC9lxDQGoOrkuyuXJC8qxY8KgEYJmIFcqCR6PWf5NA25\nfopXHNSi2QUZiA8PR0ottFSg7mm3LmFIeR3z6iT9jRJoUSD1VYXOLqPZi4F\/VdFi\n0qVV6a9JxFbGmm5U7KXn8J481WNADzTCcxduiJnZNE7+QHSihhBzOHm8ntaIwEhd\n1JU8RdnzAMKEBAUIFrUhAlizXCjD2Kf1DiWrt46XHH2TnP7DjOMsOfTesRecYZMn\nj80fHv3DlkUa9XeRk1\/pjNQCL4xY18XdjN+NxUHmVP2gBjMw+\/2GT+ZyaE0UPjdm\nKq1ApvcIebFxAC257WLU7ClkXArR0O866qfncESDMJPw4\/m+aKFby0ruogZ71qwc\nLmzJ0OVMfvXoGpx8sWrJiJXP9jGvP1LD4EgruTMrDcpjPt65vQxkEDfoHYYWVI4T\nNIxzUobHo1mKJ4PHzzAyXoUAlj2I8k6FDrcoteNKK+sumHGFlXoZan9ICEItPhCr\ns+rCn7HmAwialKX8+9mc6PGoy5oLB0u8w+WUp+6GnHfok5OeX3UGods1sCLy7mCW\nsjo3BpIzfuLubi914rUpCNcCAwEAAQ==\n-----END PUBLIC KEY-----\n"}
[authlib-injector] [DEBUG] Parsed metadata: APIMetadata [apiRoot=https://skin.443.fyi/api/yggdrasil/, skinDomains=[skin.443.fyi], decodedPublickey=Optional[Sun RSA public key, 4096 bits
  params: null
  modulus: 795137354250011911889657855933880742181023230647889737778721483193973873751299967352142082870912531607252974726779504673130830010504711331015288876855214276721740129406503712435793776518345776389880535990982459643352329272667157352507404119509292719007065098266809117629998291293874174392769501028895698157448373532386277414896865783909625619699024350841986234219265477703866923193696625314469505200890118244688081622273686106446169986753099530636126832576844495986987656471065271468409565349393806976809153913114085595185327428279673295241862321830647191573432645893641347824638435610103890702028156076928244622074183863690861903681456009457653993081788485509857934810263739201086608250428088354738931195486840849777995548954599367783605980512253831612428012205721743608096792801483281153884367587559653560182966681740496240856652915801195937782052407123986717300201358320204949417892891216121290099766921775213896831440049357615418941882288488397987437660079140002343256587985074891283889626839405585863112231331380951797398142064580993859810599888134046662605000801815620235753622135330185036513127304736806633989772225396121570446182793046702257401688061180252553410976042602896316153693055937953331821161327711499560068972087511
  public exponent: 65537], meta={feature.non_email_login=true, implementationName=Yggdrasil API for Blessing Skin, implementationVersion=5.1.5, links={"homepage":"https:\/\/skin.443.fyi","register":"https:\/\/skin.443.fyi\/auth\/register"}, serverName=唯蟹皮肤站}]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.Agent] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.BaseUserAuthentication] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [ConcatenateURL Workaround]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.UserType] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.legacy.LegacyMinecraftSessionService] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.legacy.LegacyUserAuthentication] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture$Type] with [Authlib Log Interceptor]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Transformed [com.mojang.authlib.properties.Property] with [Yggdrasil Public Key Transformer]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Httpd is running on port 46843
[authlib-injector] [DEBUG] Transformed url [https://api.mojang.com/profiles/] to [http://127.0.0.1:46843/https/api.mojang.com/profiles/]
[authlib-injector] [DEBUG] Transformed url [https://api.mojang.com/profiles/] to [http://127.0.0.1:46843/https/api.mojang.com/profiles/]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Authlib Log Interceptor]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Constant URL Transformer]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [DEBUG] Transformed url [https://sessionserver.mojang.com/session/minecraft/profile/] to [http://127.0.0.1:46843/https/sessionserver.mojang.com/session/minecraft/profile/]
[authlib-injector] [DEBUG] Transformed url [https://sessionserver.mojang.com/session/minecraft/profile/] to [http://127.0.0.1:46843/https/sessionserver.mojang.com/session/minecraft/profile/]
[authlib-injector] [DEBUG] Transformed url [https://sessionserver.mojang.com/session/minecraft/join] to [http://127.0.0.1:46843/https/sessionserver.mojang.com/session/minecraft/join]
[authlib-injector] [DEBUG] Transformed url [https://sessionserver.mojang.com/session/minecraft/hasJoined] to [http://127.0.0.1:46843/https/sessionserver.mojang.com/session/minecraft/hasJoined]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Authlib Log Interceptor]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Constant URL Transformer]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com/authenticate] to [https://skin.443.fyi/api/yggdrasil/authserver/authenticate]
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com/authenticate] to [https://skin.443.fyi/api/yggdrasil/authserver/authenticate]
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com/refresh] to [https://skin.443.fyi/api/yggdrasil/authserver/refresh]
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com/validate] to [https://skin.443.fyi/api/yggdrasil/authserver/validate]
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com/invalidate] to [https://skin.443.fyi/api/yggdrasil/authserver/invalidate]
[authlib-injector] [DEBUG] Transformed url [https://authserver.mojang.com/signout] to [https://skin.443.fyi/api/yggdrasil/authserver/signout]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Authlib Log Interceptor]
[authlib-injector] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Constant URL Transformer]
[authlib-injector] [DEBUG] Adding callback metafactory
[authlib-injector] [DEBUG] Upgrading class version from 50 to 51
[authlib-injector] [INFO] Registered log handler on sun.misc.Launcher$AppClassLoader@18b4aac2
[authlib-injector] [DEBUG] Query profile of [e8b46b33-3e17-4b64-8d07-9af116df7d3b] at [https://skin.443.fyi/api/yggdrasil/], not found
[authlib-injector] [DEBUG] Request to [/https/sessionserver.mojang.com/session/minecraft/profile/e8b46b333e174b648d079af116df7d3b] is handled by [moe.yushi.authlibinjector.httpd.QueryProfileFilter@43c0bf42]

**Comment by yushijinhun** [comment]
你是不是装了 NonUpdate？

**Comment by HoratioShaw** [comment]
没有

发件人: Haowei ***@***.***>
发送时间: 2022年8月6日 8:23
收件人: ***@***.***>
抄送: Horatio ***@***.***>; ***@***.***>
主题: Re: [yushijinhun/authlib-injector] 身份认证目前正在停机维护 (Issue #173)


你是不是装了 NonUpdate？

―

**Comment by yushijinhun** [comment]
你确定客户端也没有安装 NonUpdate 吗？如果问题依然存在，请加 Telegram 或者 QQ 群，可以帮你远程看一下，链接在 Wiki 首页。

**Comment by HoratioShaw** [comment]
> 你确定客户端也没有安装 NonUpdate 吗？如果问题依然存在，请加 Telegram 或者 QQ 群，可以帮你远程看一下，链接在 Wiki 首页。

不好意思，之前只看了服务端没看客户端，去除这个mod以后正常了
