### ISSUE TITLE
局域网无法通过验证，客户端提示“登陆失败：无效会话”

### ISSUE THREAD

**Issue by Jason-2048** [yushijinhun/authlib-injector#177]
客户端为官服1.19，启动参数为
`@ECHO OFF`
`java -Xmx10G -Xms512M -XX:+UseG1GC -javaagent:authlib-injector-1.2.1.jar=https://mcskin.cn/api/yggdrasil -Dauthlibinjector.noShowServerName -Dauthlibinjector.mojangAntiFeatures=disabled -Dauthlibinjector.usernameCheck=disabled -jar server.jar nogui`
`pause`
server.properties 中 
`enforce-secure-profile=true`
`online-mode=true`
服务端日志为
`[12:02:34] [Server thread/INFO]: com.mojang.authlib.GameProfile@41d1c566[id=<null>,name=***,properties={},legacy=false] (/192.168.3.150:49392) lost connection: Disconnected`

**Comment by Jason-2048** [comment]
8月5号加载了authlib-injector-1.2.0.jar，直至12号上午还能正常登陆，晚上就不行了，13号早上尝试更新版本指1.2.1，问题重现

**Comment by yushijinhun** [comment]
`prevent-proxy-connections` 选项默认就是关闭的，我不知道为什么你会打开。

Blessing Skin 对 `prevent-proxy-connections` 的实现存在问题，最好不要使用此功能。

**Comment by Jason-2048** [comment]
> `prevent-proxy-connections` 选项默认就是关闭的，我不知道为什么你会打开。
> 
> Blessing Skin 对 `prevent-proxy-connections` 的实现存在问题，最好不要使用此功能。

我没有打开啊。。本身就是关的，我也没有去动他，只是确保关闭。。

**Comment by yushijinhun** [comment]
邮箱大小写不一致可能确实会造成问题，这应该是 Blessing Skin 的 bug。
