### ISSUE TITLE
正版用户登录服务器提示：验证用户名失败

### ISSUE THREAD

**Issue by DomnickJYH** [yushijinhun/authlib-injector#179]
我自己知道为何正版用户不能直接登录使用了 authlib-injector 的服务器的原因：玩家和服务端使用的验证服务器不同，正版玩家进服时是向 Mojang 的验证服务器请求进服验证，而服务端是向服主自己实现的验证服务器请求验证进服请求，两边的数据不互通，自然服务端使用的验证服务器无法验证正版玩家的进服请求，当然就返回错误了。
主要就是希望得到相关解决方法，使得正版用户能直接登录使用了 authlib-injector 的服务器。

**Comment by yushijinhun** [comment]
authlib-injector 的设计目标**不包括**允许正版用户进服，也**不包括**允许多个不同验证服务器的玩家进服，因为这在技术上存在无法规避的问题。

如果你真的想要这么做，请参考 https://github.com/CaaMoe/MultiLogin
