### ISSUE TITLE
[功能请求]提供选项当已设定URL后登陆失败使用官方API

### ISSUE THREAD

**Issue by Small-Miao** [yushijinhun/authlib-injector#182]
如标题 我想问问是否可以在设定好 外置登录API后 如果登录失败 将请求转发至Mojang官方API请求登陆
这样既可以兼容正版以及没有正版的玩家

**Comment by DreamOneX** [comment]
建议搜一下issue
找到这样的回复应该不难
* https://github.com/yushijinhun/authlib-injector/issues/179#issuecomment-1221630190
* https://github.com/yushijinhun/authlib-injector/issues/171#issuecomment-1196783821

**Comment by Small-Miao** [comment]
感谢回复
