### ISSUE TITLE
登陆游戏后发送消息时出现“由于个人信息公钥丢失，聊天已被禁用。请尝试重新连接。”

### ISSUE THREAD

**Issue by qilaoshi219** [yushijinhun/authlib-injector#192]
mc版本是：1.19.3
ai版本是：1.2.1
可以正常进入游戏，但无法发送消息，发送消息后会出现”由于个人信息公钥丢失，聊天已被禁用。请尝试重新连接。“的提示。
服务端无报错
![2023-01-01_19 54 12](https://user-images.githubusercontent.com/56624923/210169802-9a0f76d3-e145-4cf4-84ff-fcd6bdf36717.png)

**Comment by Laotaoz** [comment]
游戏版本：1.19.3
AuthLib-Injector版本：1.2.1

请将server.properties文件中的enforce-secure-profile改为false
参考链接:https://www.mcbbs.net/thread-1374418-1-1.html

我找了一天，就是没往服务器配置文件上想。。

**Comment by yushijinhun** [comment]
目前（authlib-injector v1.2.0+）将 enforce-secure-profile 设置为 true 可以正常游戏。如果还有问题，请 reopen 此 issue。
