### ISSUE TITLE
开启enforce-secure-profile则会导致java端无法发送消息，如果关闭则会导致”出现无法验证聊天消息“的弹窗

### ISSUE THREAD

**Issue by qilaoshi219** [yushijinhun/authlib-injector#193]
游戏版本：1.19.3
ai版本1.2.1

想要请教一下没有两全的解决方案吗

**Comment by heipiao233** [comment]
办法倒是有，要你的玩家装 [这个模组](https://www.mcmod.cn/class/7054.html)

**Comment by yushijinhun** [comment]
目前（authlib-injector v1.2.0+）将 `enforce-secure-profile` 设置为 `true` 可以正常游戏，不会弹窗。
