### ISSUE TITLE
提示“登录失败:身份验证系统正在停机维护”

### ISSUE THREAD

**Issue by TomatoGarden666** [yushijinhun/authlib-injector#196]
是这样的，我用Blessing Skin Server搭建了一个皮肤站。里面有了“Yggdrasil Api”，我开启了它。也提供了地址：
![image](https://user-images.githubusercontent.com/94282242/218243033-471e2194-a7f5-480c-827e-bb14f018564b.png)
我使用此地址登录了，同时也成功了，服务器端配置也没有问题。
但是无论我使用哪个启动器，都是会出现标题上的问题。
希望可以得到解决，还有一个重要的：我使用了CloudFlare。

**Comment by 8MiYile** [comment]
先尝试关闭Cloudflare的网站CDN功能 就是仅DNS模式下连入该网站

**Comment by hayptnplay** [comment]
好的我try一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yushijinhun/authlib-injector] 提示“登录失败:身份验证系统正在停机维护” (Issue #196)




 
先尝试关闭Cloudflare的网站CDN功能 就是仅DNS模式下连入该网站

**Comment by hayptnplay** [comment]
但是我使用了CloudFlare的加密功能，如果不使用就会变成HTTP



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上9:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [yushijinhun/authlib-injector] 提示“登录失败:身份验证系统正在停机维护” (Issue #196)




 
先尝试关闭Cloudflare的网站CDN功能 就是仅DNS模式下连入该网站

**Comment by 8MiYile** [comment]
建议在网站本身就要开启SSL

**Comment by TomatoGarden666** [comment]
但是我使用了wampserver，配置超麻烦，而且还会不成功



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 下午5:59
收件人: ***@***.***&gt;;
抄送: "Guancheng ***@***.******@***.***&gt;;
主题: Re: [yushijinhun/authlib-injector] 提示“登录失败:身份验证系统正在停机维护” (Issue #196)




 
建议在网站本身就要开启SSL

**Comment by 8MiYile** [comment]
这。。什么鬼啊喂。。

**Comment by TomatoGarden666** [comment]
就是说在apatch官网也有这个推荐的，也挺好用，但是不知道为什么不能配置ssl



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 晚上8:35
收件人: ***@***.***&gt;;
抄送: "Guancheng ***@***.******@***.***&gt;;
主题: Re: [yushijinhun/authlib-injector] 提示“登录失败:身份验证系统正在停机维护” (Issue #196)




 
这。。什么鬼啊喂。。

**Comment by TomatoGarden666** [comment]
要不加个Q方便联系？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月18日(周六) 晚上8:35
收件人: ***@***.***&gt;;
抄送: "Guancheng ***@***.******@***.***&gt;;
主题: Re: [yushijinhun/authlib-injector] 提示“登录失败:身份验证系统正在停机维护” (Issue #196)




 
这。。什么鬼啊喂。。

**Comment by TomatoGarden666** [comment]
ok啊我把cloudflare代理换成了普通的SSL，但是直接就显示无法连接到认证服务器了，这该怎么办？

**Comment by 8MiYile** [comment]
是直连吗？因为这个因素 和你的服务端程序 以及你所使用的皮肤站（例如Blessing Skin）有关系，这不仅仅只是客户端问题，甚至还涉及到服务端的Nginx，就算Nginx正常，也不代表你的皮肤站也是正常的。。。如果有必要，可以查看一下你的皮肤站如何开启调试模式来确认原因，以及Nginx那边的调试模式，用于查看连接记录

**Comment by TomatoGarden666** [comment]
虽然但是，我用的是Apache，一般来说是不会的，对了，你这里的“直连”指的是什么？服务器还是？

**Comment by 8MiYile** [comment]
客户端——Apache——PHP——BlessingSkin(或者其他皮肤站)
从这四个因素找

**Comment by qwq233** [comment]
@8MiYile 从运行mc的服务端curl皮肤站什么表现

**Comment by TomatoGarden666** [comment]
我是都试过安装其他的东西，php和apache是没有问题的，客户端也没有，是新下载的，那么可能在其他问题上，因为皮肤站可以正常访问


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月15日(周三) 晚上9:11
收件人: ***@***.***&gt;;
抄送: &quot;Guancheng ***@***.******@***.***&gt;;
主题: Re: [yushijinhun/authlib-injector] 提示&ldquo;登录失败:身份验证系统正在停机维护&rdquo; (Issue #196)




 
客户端——Apache——PHP——BlessingSkin(或者其他皮肤站)
 从这四个因素找
 
&mdash;

**Comment by TomatoGarden666** [comment]
这我不知道，怎么才能知道？平时我都不看这些，最近忙着搭建服务器了@qwq233

**Comment by yushijinhun** [comment]
由于不活动关闭此 issue。

@TomatoGarden666 如果你的问题依然存在，请 reopen 此 issue。同时，在客户端开启 `-Dauthlibinjector.debug` 然后使用 HMCL 的调试模式启动游戏，上传控制台输出。
