### ISSUE TITLE
【Question】关于AGPL例外情况

### ISSUE THREAD

**Issue by 8MiYile** [yushijinhun/authlib-injector#197]
https://github.com/yushijinhun/authlib-injector/blob/develop/README.md?plain=1#L125

若对于是以插件形式实现了AuthLib-Injector的功能
`比如通过Velocity的插件系统加载了MultiLogin就是实现了AuthLib-Injector`
是否也得写在上边 以告示那些基于AuthLib-Injector开发的开发者 要在他们的项目的Credit上标注？

**Comment by yushijinhun** [comment]
AGPL 和 Credit 没有关系。
