### ISSUE TITLE
1.19.4客户端无法正常获取皮肤

### ISSUE THREAD

**Issue by GLDYM** [yushijinhun/authlib-injector#199]
当使用装有authlib-injector的1.19.4的客户端进入装有authlib-jector的服务端时，客户端能正常连接到皮肤站（开始界面左下角有皮肤站名称），但玩家的皮肤为默认皮肤。
原因似乎是因为在1.19.4中更换了内置的皮肤域名黑白名单位置，导致无法正常从非官方皮肤站获取皮肤。

**Comment by coldshineb** [comment]
我在使用1.19.3客户端进入1.19.3服务器（服务器开启了跨版本和基岩版进服支持）时也有此问题

**Comment by yushijinhun** [comment]
已在 v1.2.2 中修复。
