### ISSUE TITLE
[proposal] CORS 支持

### ISSUE THREAD

**Issue by yushijinhun** [yushijinhun/authlib-injector#20]
## 概述
此提案旨在要求 Yggdrasil 服务端对部分 API 启用 [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)，以允许其被其他站点上的网页应用调用。

## 实现
在 CORS Preflight 请求的响应中，Yggdrasil 服务端应包含以下头字段：
* `Access-Control-Allow-Origin: *`
    * 允许来自任意站点的请求。
* `Access-Control-Expose-Headers: X-Authlib-Injector-API-Location`
    * 允许浏览器将 ALI 头（见 #18）暴露给网页应用。
* `Access-Control-Allow-Methods`
    * 此头字段的值为允许的请求方法，会在下面具体说明。

Yggdrasil 服务端应对以下 API 开启 CORS（其他的也可以开启，但不作强制要求）：
* [查询角色属性](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E6%9F%A5%E8%AF%A2%E8%A7%92%E8%89%B2%E5%B1%9E%E6%80%A7) `/sessionserver/session/minecraft/profile/{uuid}`
    * 允许的请求方法：GET
* [按名称批量查询角色](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E6%8C%89%E5%90%8D%E7%A7%B0%E6%89%B9%E9%87%8F%E6%9F%A5%E8%AF%A2%E8%A7%92%E8%89%B2) `/api/profiles/minecraft`
    * 允许的请求方法：POST
* [服务端信息获取](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E6%9C%8D%E5%8A%A1%E7%AB%AF%E4%BF%A1%E6%81%AF%E8%8E%B7%E5%8F%96) `/`
    * 允许的请求方法：GET
* 皮肤站首页，或者其他你想要公开 ALI 的页面
    * 允许的请求方法：GET
    * 这将允许网页应用读取皮肤站首页的内容，进而通过 ALI 得到 Yggdrasil API 的地址。

## 安全考虑
*  CORS Preflight 请求的响应中，**不允许**包含 `Access-Control-Allow-Credentials: true` 头字段。
    * 当你在非 Yggdrasil API 接口（如上文中的皮肤站首页）上开启 CORS 时，尤其要注意这一点。否则恶意页面可以窃取 CSRF Token，进而发起 CSRF 攻击。
* 当皮肤站处于内网时，应谨慎开启 CORS，否则可能导致数据泄露。
    * 恶意网页可以通过 CORS 访问到处于内网的皮肤站（而该皮肤站在外网无法被访问），进而导致数据泄露。

---
### 欢迎诸位就本提案提出意见。

**Comment by yushijinhun** [comment]
@printempw 那改成一个建议如何？让皮肤站酌情选择是否实现。如果要实现，则给出上面的内容作为参考。

**Comment by printempw** [comment]
在皮肤站的 Yggdrasil API 插件中提供开启 CORS 的选项是可行的（我觉得应该默认关闭）。

**Comment by yushijinhun** [comment]
其实如果作为建议，我觉得都是废话。
