### ISSUE TITLE
关于无法正常启动服务器

### ISSUE THREAD

**Issue by TomatoGarden666** [yushijinhun/authlib-injector#200]
我使用的是Waterfall
日志内容如下：
Logging started at 2023-03-19T03:45:04.720762200Z
[authlib-injector] [INFO] Version: 1.2.1
[authlib-injector] [INFO] Authentication server: https://skin.haysoft.top/api/yggdrasil
[authlib-injector] [ERROR] Failed to fetch metadata: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

服务器就不能启动了，皮肤站可以正常访问。

上链接：<a href="https://skin.haysoft.top/">链接</a>

**Comment by TomatoGarden666** [comment]
PCL启动器可以正常使用（这个皮肤站），而HMCL就不行

这是皮肤站的问题还是？

**Comment by qwq233** [comment]
@TomatoGarden666 证书链不齐全

**Comment by TomatoGarden666** [comment]
@qwq233 那我应该怎么办？是去重新签发一张证书吗？

**Comment by qwq233** [comment]
@TomatoGarden666 补全啊
Google 证书链补全

**Comment by TomatoGarden666** [comment]
ok

**Comment by TomatoGarden666** [comment]
我去试试

**Comment by qwq233** [comment]
@TomatoGarden666 * GitHub不是及时性通讯软件

**Comment by TomatoGarden666** [comment]
非常感谢！问题已解决！
