### ISSUE TITLE
Android手机上使用authlib-injector一些问题

### ISSUE THREAD

**Issue by root-S7** [yushijinhun/authlib-injector#207]
Android的一些游戏启动器（如Pojav，澪，HMCL-PE...），在使用Java8 + authlib-injector直接崩溃，我排查到似乎是下面这条启动参数导致的。
-javaagent:/storage/emulated/0/UZMap/authlib-injector.jar=https://littleskin.cn/api/yggdrasil/
**我还注意到貌似只有LittleSkin，Blessing Skin这两个平台有问题，其他皮肤站平台都没有

切换到Java17环境并没有崩溃问题且可以正常进入游戏；只有Java8环境有这个问题**
崩溃日志：（没有游戏崩溃日志，只有authlib-injector.log的）
[authlib-injector.log](https://github.com/yushijinhun/authlib-injector/files/11500571/authlib-injector.log)
这是Java8环境的启动参数：
[参数.txt](https://github.com/yushijinhun/authlib-injector/files/11500601/default.txt)

**Comment by yushijinhun** [comment]
LittleSkin 的问题，已通知其解决。
