### ISSUE TITLE
查看插件市场报错 Undefined array key "packages"

### ISSUE THREAD

**Issue by by123456by** [yushijinhun/authlib-injector#210]
![image](https://github.com/yushijinhun/authlib-injector/assets/15666692/23e4818e-8e37-4fa2-856c-f89ed99c8a52)
[laravel-2023-06-11.log](https://github.com/yushijinhun/authlib-injector/files/11712813/laravel-2023-06-11.log)
系统:CentOS 7.9.2009 x86_64(Py3.7.9)
宝塔：7.9.6
nginx：Nginx 1.20.1
php：PHP-8.1.17
mysql：MySQL 5.7.34
uri：/admin/plugins/market

**Comment by yushijinhun** [comment]
与本项目无关，请到 https://github.com/bs-community/blessing-skin-server 反馈。
