### ISSUE TITLE
服务端启动时报错

### ISSUE THREAD

**Issue by Pikachu-xy** [yushijinhun/authlib-injector#214]
服务端启动时报错，authlib-injector.log的内容如下：
```
Logging started at 2023-06-29T15:11:37.174560200Z
[authlib-injector] [INFO] Version: 1.2.3
[authlib-injector] [INFO] Authentication server: https://littleskin.cn/api/yggdrasil
[authlib-injector] [ERROR] Failed to fetch metadata: java.net.ConnectException: Connection refused: connect
```
服务端启动指令如下：
`java -Xms3G -Xmx3G -javaagent:authlib-injector-1.2.3.jar=https://littleskin.cn/api/yggdrasil -jar forge-1.12.2-14.23.5.2860.jar`

**Comment by yushijinhun** [comment]
你执行下 `nslookup littleskin.cn` 看看输出？

**Comment by Pikachu-xy** [comment]
```
C:\Users\Pikachu_xy>nslookup littleskin.cn
服务器:  192.168.1.1
Address:  192.168.1.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
非权威应答:
名称:    opencdnv6.tzcdn.idcloudbase.com
Addresses:  240e:978:6402::b461:c623
          0.0.0.0
Aliases:  littleskin.cn
          littleskin.cn.a.bdydns.com
          opencdnv6.jomodns.com
```

**Comment by yushijinhun** [comment]
你的 DNS 查询结果中包含 `0.0.0.0`，说明你可能遇到了 DNS 污染。你可以把系统的 DNS 设置修改为 `223.5.5.5`、`223.6.6.6`（AliDNS），然后再运行 `nslookup littleskin.cn` 看看。

**Comment by Pikachu-xy** [comment]
```
C:\Users\Pikachu_xy>nslookup littleskin.cn
服务器:  public1.alidns.com
Address:  223.5.5.5

非权威应答:
名称:    opencdnv6.jomodns.com
Addresses:  240e:979:9503:6::72e8:5c23
          180.122.77.35
          106.225.194.35
Aliases:  littleskin.cn
          littleskin.cn.a.bdydns.com
```

**Comment by Pikachu-xy** [comment]
我刚刚尝试了一下可以正常启动服务端了，很感谢你的解答

**Comment by yushijinhun** [comment]
这说明你的路由器使用的 DNS 被污染了，它使用的 DNS 一般是由运营商下发的。方便的话，你可以登录你路由器后台，看一下路由器上的 DNS 是什么，然后在这里贴出你所在的城市、运营商和 DNS。

**Comment by Pikachu-xy** [comment]
所在城市：福州
运营商：中国电信
路由器DNS：`218.85.157.99`，`218.85.152.99`

**Comment by yushijinhun** [comment]
我这边无法用你提供的 DNS 查询，可能是福州电信的 DNS 服务器阻止了其他地区用户的访问。但是，福州地区已知会对部分域名进行 DNS 污染，你可以执行 `nslookup littleskin.cn 218.85.157.99` 看下结果中是否包含 `0.0.0.0`。如果有，那就说明你的运营商污染了 LittleSkin 的域名，请向你的运营商投诉，让他们停止这种流氓行为（如果拨打运营商客服电话无效，可以向工信部投诉）。
