### ISSUE TITLE
聊天"个人信息公钥丢失"

### ISSUE THREAD

**Issue by ruattd** [yushijinhun/authlib-injector#217]
如题，玩家在聊天栏发送消息时提示"个人信息公钥丢失"

Minecraft Server 1.20.1 (Paper)
authlib-injector 1.2.3 with littleskin.cn
enforce-secure-profile=true

**Comment by Silverteal** [comment]
客户端是否使用了authlib-injector并更新到1.2.x版本?
authlib-injector应该会代理聊天签名。

**Comment by ruattd** [comment]
当时的环境同为 1.2.3 ，但是那个环境已经不在了，我自己现在也复现不了它，等它下次发生我再来开一个 issue 吧
