### ISSUE TITLE
Minecraft 1.20.5 and 1.20.6 support

### ISSUE THREAD

**Issue by Proxwian** [yushijinhun/authlib-injector#244]
LinkageError occurred while loading main class net.minecraft.client.main.Main
	java.lang.UnsupportedClassVersionError: net/minecraft/client/main/Main has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

**Comment by tnqzh123** [comment]
This is not caused by authlib-injector, but your Java.

Since 1.20.5, Minecraft requires Java 21 to run. Please upgrade your Java.

**Comment by Proxwian** [comment]
That's right. My bad
