### ISSUE TITLE
blocked domain

### ISSUE THREAD

**Issue by zrll12** [yushijinhun/authlib-injector#258]
我在写一个服务端的实现，游戏后台报错textures payload contains blocked domain，无法显示皮肤

想问一下blocked domain都包括哪些？有什么办法设置吗

**Comment by yige233** [comment]
[Yggdrasil-服务端技术规范#材质域名白名单](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E6%9D%90%E8%B4%A8%E5%9F%9F%E5%90%8D%E7%99%BD%E5%90%8D%E5%8D%95)

需要在元数据API下面加上材质域名

**Comment by zrll12** [comment]
元数据返回信息为："skinDomains":["http://127.0.0.1:7890"]
url是http://127.0.0.1:7890/textures/TnCgtZBU8wUCsn4g5gqpzcgoHc-hpXNLOxlrJM0hxFQ
应该已经正确设置了啊

**Comment by yige233** [comment]
你填的这个格式不对

>  如果规则以 .（dot）开头，则匹配以这一规则结尾的域名。
>  例如 .example.com 匹配 a.example.com、b.a.example.com，不匹配 example.com。
>  如果规则不以 .（dot）开头，则匹配的域名须与规则完全相同。
>  例如 example.com 匹配 example.com，不匹配 a.example.com、eexample.com。

填`127.0.0.1`应该就可以了

**Comment by zrll12** [comment]
解决了
