### ISSUE TITLE
有可能实现兼容MMC启动器吗？

### ISSUE THREAD

**Issue by huangsijun17** [yushijinhun/authlib-injector#26]
有没有可能通过在MMC的“实例”中新建“项”来加载authlib-injector？或者别的方法实现直接兼容呢？

**Comment by yushijinhun** [comment]
登录需要启动器支持，如果 MultiMC 不支持这个那就是不能用的。

**Comment by huangsijun17** [comment]
前些天试了一下，在MultiMC的启动参数中加入`-javaagent:{authlib-injector.jar 的路径}={验证服务器 URL (API 地址)}`是可以不需要二次登陆就能进Yggdrasil 服务端的。

**Comment by yushijinhun** [comment]
不是还需要 UUID 以及 accessToken 吗？不太清楚你是如何做到的。

**Comment by huangsijun17** [comment]
![image](https://user-images.githubusercontent.com/31504595/121778712-b8408300-cbca-11eb-8b88-d49ac7baf7f1.png)
这样登录就进去了。
因为MultiMC必须使用正版，所以会使用正版的邮箱和密码去登录，获取Mojang的 UUID 以及 accessToken 。
之前我是试过使用游戏内的登录MOD，重新登陆一次来进使用统一通行证的服务器。

**Comment by huangsijun17** [comment]
https://paste.ubuntu.com/p/KkZtHV4kmK/
这是本地时启动的log。

**Comment by yushijinhun** [comment]
那你进入的是正版服务器，还是用了 authlib-injector 的服务器？如果是后者的话，你进服时候用的 accessToken 是 Mojang 的，而不是自定义验证服务的，照理是进不去的。（除非验证服务器做了特殊处理）

或者说你的服务器压根没开 online-mode？

**Comment by huangsijun17** [comment]
> 那你进入的是正版服务器，还是用了 authlib-injector 的服务器？如果是后者的话，你进服时候用的 accessToken 是 Mojang 的，而不是自定义验证服务的，照理是进不去的。（除非验证服务器做了特殊处理）
> 
> 或者说你的服务器压根没开 online-mode？

服务器说是用了 authlib-injector 的服务器。

**Comment by yushijinhun** [comment]
看起来是 BS 的一个功能。

https://github.com/bs-community/blessing-skin-plugins/commit/fe722936238a4d9e304b57a54df35646e22616fc

**Comment by huangsijun17** [comment]
我自己搭一个，试试看吧。

> 看起来是 BS 的一个功能。
> 
> [bs-community/blessing-skin-plugins@fe72293](https://github.com/bs-community/blessing-skin-plugins/commit/fe722936238a4d9e304b57a54df35646e22616fc)

可还行，这么说来，使用官方启动器和MultiMC的，可以很方便得进入了。

**Comment by yushijinhun** [comment]
确实如此。在 BS 上绑定了 Mojang 账户的用户，使用自定义验证服务只需要正版登录 + authlib-injector 参数就行了。

不过这应该只在启动器不支持 authlib-injector 的情况下有使用价值。
