### ISSUE TITLE
Forge客户端在服务器内只能看见自己皮肤

### ISSUE THREAD

**Issue by KichikuNya** [yushijinhun/authlib-injector#33]
在原版游戏内没有问题，只发生在装有forge的客户端
游戏内皮肤、TAB的头像只有自己的是正确的，其他玩家都是史蒂夫或者阿利克斯
其他需要显示玩家头像的mod均能显示正确的头像，小地图、墓碑等
游戏版本1.12.2
forge版本尝试过2705、2768、2807都有问题
authlib-injector版本1.1.24-fe7cb0b

**Comment by yushijinhun** [comment]
已确认

**Comment by yushijinhun** [comment]
此 bug 在 https://github.com/yushijinhun/authlib-injector/commit/ffd2a94b3d624c19b0d336ba4ece938346f404a8 引入，原因是 Forge 的 ClassLoader 没有按照双亲委派模型去加载 authlib-injector 的类。

**Comment by KichikuNya** [comment]
> 
> 
> 此 bug 在 [ffd2a94](https://github.com/yushijinhun/authlib-injector/commit/ffd2a94b3d624c19b0d336ba4ece938346f404a8) 引入，原因是 Forge 的 ClassLoader 没有按照双亲委派模型去加载 authlib-injector 的类。

这么快就查出来了吗
