### ISSUE TITLE
Workaround for MC-52974 (1.7.10)

### ISSUE THREAD

**Issue by yushijinhun** [yushijinhun/authlib-injector#35]
这个 issue 是从 #30 中独立出来的。

在 MC 1.7.10 中，MC-52974 这个 bug 是由以下两个问题造成的：
1. Host 在查询自己的 GameProfile 时，没有查询数字签名，因此其向 Guest 所发送的 Textures payload 中也不可能包含数字签名。
2. Host 根本没有向 Guest 发送 GameProfile 中的 properties。

第一个问题已在 #31 中解决。在和 @NekoCaffeine 讨论后，我找到了造成第二个问题的原因：
1. `net.minecraft.util.Session`负责创建`GameProfile`对象，每次进服（包括本地游戏）时，它就创建一个。其创建的`GameProfile`不包含properties。
2. 创建的`GameProfile`被放入`C00PacketLoginStart`中，不经过序列化直接被传递到本地服务器。
3. 本地服务器取出`C00PacketLoginStart`中的`GameProfile`对象。因为进入本地游戏时不经过`KEY`阶段，直接跳到`READY_TO_ACCEPT`阶段，所以不会去调用hasJoined接口，所以本地服务器使用的`GameProfile`对象直接就是一开始`Session`所创建的对象。
4. 因为`GameProfile`不包含properties，所以发送的`S0CPacketSpawnPlayer`中也不包含properties。
5. `SkinManager`中存在逻辑：加载皮肤时，如果properties为空，并且加载的是自己的皮肤，就去查询皮肤。所以Host可以看到自己的皮肤，而Guest不能看到Host皮肤。

我所给出的解决方法：
1. 修改`Session`，对其创建的`GameProfile`对象进行标记。
2. 修改`S0CPacketSpawnPlayer`，当包被序列化时，如果其中的`GameProfile`是被标记过的，就查询properties并加入其中。

**Comment by yushijinhun** [comment]
@NekoCaffeine @andylizi 我在 https://github.com/yushijinhun/authlib-injector/commit/f2a447d58d3ac4ef77d349f25c3819874319ae5d 中实现了这个 Workaround，并且在 1.7.10 原版上测试通过。但是我有以下问题：
1. 我在代码中硬编码了混淆后的标识符名称，这么做是否靠谱？
2. 我没有检测 MC 版本就改了字节码，会不会误伤其他版本？

**Comment by andylizi** [comment]
我只能建议说参考一下其他改字节码的 mod 是怎么实现的。

**Comment by yushijinhun** [comment]
我对这方面并不是很懂，不知您是否能解释下？ @andylizi

**Comment by andylizi** [comment]
我虽然比较了解字节码，但我也不懂 mod……

好像 Forge 的代码里面就有解决这个问题？之前看到一个 [forge_at.srg](https://github.com/MinecraftForge/MinecraftForge/blob/1.12.x/src/main/resources/forge_at.cfg) 里面放了 mcp name 到 srg name 的映射。可能跟这个有关系？或者去 [net.minecraftforge.fml.common.asm](https://github.com/MinecraftForge/MinecraftForge/tree/1.12.x/src/main/java/net/minecraftforge/fml/common/asm) 包里看看？

**Comment by yushijinhun** [comment]
我在 #37 里实现了。
