### ISSUE TITLE
关于Bungeecord的连接出错

### ISSUE THREAD

**Issue by thanksshu** [yushijinhun/authlib-injector#44]
1. 在按照Wiki指示配置服务端：
 - 在Bungeecord和服务端各加载API成功、
 - 二者Online模式都按要求设置完成、
 - 确认服务端可以直接连接
的情况下，连接Bungeecord，出现：
“Exception Connecting:Quiet Exception :Unexpected Packet received during serveur  login processus
1bcc017b227472616e736c617465223a”
2. 检查配置发现Bungeecord存在
 * ip_fowarding
一项默认开启，
3. 禁用此项、重启、尝试连接后方可成功。
----这仅仅是巧合还是配置方面需要额外加以注意的地方？

**Comment by yushijinhun** [comment]
如果不加载authlib-injector，即使用正版验证，会不会出现此状况？

**Comment by thanksshu** [comment]
依旧会出现问题啊——这样看来API没有问题，应该是BungeeCord的问题，打扰了，请关闭这个Issue。

**Comment by NekoCaffeine** [comment]
spigot?
是的话 spigot.yml 的 bungeecord 字段是否为 true
