### ISSUE TITLE
【偷懒计划】这样偷懒N下是否可行

### ISSUE THREAD

**Issue by ShangJixin** [yushijinhun/authlib-injector#45]
1.不去做令牌的生命周期，取而代之的是在MySQL存储玩家的accesstoken和clinttoken。这样的话 /refresh 接口就可以万年不用调用了 哈哈哈哈
如果有新的token，直接覆盖掉原有的数据，保证数据库内玩家有且仅有一个accesstoken和clinttoken

2.不自己实现皮肤站的功能，想办法实现一个与Mojang正版账号绑定的功能，然后通过Mojang的api给玩家发放皮肤，自建ygg后端不进行存储皮肤文件

3.还有其他可以偷懒的可行办法吗

（打算用php搞，这块提供的方案是java的，想少造点轮子）

4.（从bs皮肤站作者那里看到的）

> 初次登录时，用账号密码拿到 AccessToken
> POST /authserver/authenticate
> 之后的登录都是直接用这个 API 签发新的令牌
> POST /authserver/refresh
> 加入服务器
> POST /sessionserver/session/minecraft/join
> 验证是否加入了服务器
> GET  /sessionserver/session/minecraft/hasJoined
> 获取玩家完整 Profile
> GET  /api/profiles/minecraft/{uuid}

仅用这五个api，可以满足日用吗（有点好奇qwq）

添加：
还有一个...如果我把进服的joinId这么处理 （有可能没法用redis那类东西做）

客户端post过来joinid，入库joinid
服务端发送get请求来校验joinid
然后跟mysql库里的那个进行比对
比对完成后，数据库里的“最后joinid”不抹除，等待下一次请求时自动由第一步覆盖

这样弄的话...会不会有安全性问题

**Comment by ShangJixin** [comment]
还有一个...如果我把进服的joinId这么处理 （有可能没法用redis那类东西做）

客户端post过来joinid，入库joinid
服务端发送get请求来校验joinid
然后跟mysql库里的那个进行比对
比对完成后，数据库里的“最后joinid”不抹除，等待下一次请求时自动由第一步覆盖

这样弄的话...会不会有安全性问题

**Comment by hempflower** [comment]
这样做貌似打破了规范？

**Comment by yushijinhun** [comment]
> 如果有新的token，直接覆盖掉原有的数据，保证数据库内玩家有且仅有一个accesstoken和clinttoken

首先是 **clientToken** 不是 clinttoken。如果你这么做的话，用户将不能多开。也就是说，当你在不同启动器间切换时，都需要重输密码。并且如果你打算实现多角色功能，那么在角色间切换时也需要重输密码。

---

> 不自己实现皮肤站的功能，想办法实现一个与Mojang正版账号绑定的功能，然后通过Mojang的api给玩家发放皮肤，自建ygg后端不进行存储皮肤文件

可以。

---

> 还有其他可以偷懒的可行办法吗

不知道。

---

> 仅用这五个api，可以满足日用吗（有点好奇qwq）

这五个是最低要求。

---

> 客户端post过来joinid，入库joinid
> 服务端发送get请求来校验joinid
> 然后跟mysql库里的那个进行比对
> 比对完成后，数据库里的“最后joinid”不抹除，等待下一次请求时自动由第一步覆盖
>
> 这样弄的话...会不会有安全性问题

首先是 **serverId** 不是 joinid。安全问题没有，但是你所说的“等待下一次请求时自动由第一步覆盖”无法实现，因为每次请求的 serverId 都是不同的。
