### ISSUE TITLE
客户端启动报错

### ISSUE THREAD

**Issue by Squaregentleman** [yushijinhun/authlib-injector#46]
```
[authlib-injector.launch] [INFO] Version: 1.1.21-f242b97
[authlib-injector.config] [INFO] API root: https://skin.fkj233.cn/api/yggdrasil/
[authlib-injector.config] [SEVERE] Failed to fetch metadata: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by zhzRedstone** [comment]
> [authlib-injector.launch] [INFO] Version: 1.1.21-f242b97
> [authlib-injector.config] [INFO] API root: https://skin.fkj233.cn/api/yggdrasil/
> [authlib-injector.config] [SEVERE] Failed to fetch metadata: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

java版本，客户端版本：

**Comment by Indexyz** [comment]
服务器 HTTPS 证书不被信任

尝试补全下证书链

![IMG_20190325_085926_451](https://user-images.githubusercontent.com/7685264/54888906-59ed3400-4edc-11e9-8f6d-60db4bef777e.jpg)
