### ISSUE TITLE
Capes not visible on server

### ISSUE THREAD

**Issue by gitfamhub** [yushijinhun/authlib-injector#48]
I'm testing authlib-injector with Blessing Skin Server on a server, and while I can see my skin, capes don't seem to show. Joining a singleplayer world I can see it just fine, though.

Is it just me, or?

**Comment by yushijinhun** [comment]
Could you please test it with my authlib-injector demo server? You are expected to see both the skin and the cape if everything works fine.

Demo server:
API Root: `https://example.yggdrasil.yushi.moe/`
Username: `test2@to2mbn.org`
Password: `222222`

**Comment by gitfamhub** [comment]
Somehow it works perfect with that test account and server.

Does this mean it's an issue on BSS's end?

**Comment by yushijinhun** [comment]
It might be. Please turn on the [debug output](https://github.com/yushijinhun/authlib-injector/blob/develop/README.en.md#print-verbose-logs) on the server side with `-Dauthlibinjector.debug=all` and check what is printed.

**Comment by gitfamhub** [comment]
Sorry I'm stupid, I thought I'd deleted the elyby skins plugin but from the debug output I noticed I only did the folder and kept the jar. Deleting it fixed it.

My mistake, sorry! 😥
