### ISSUE TITLE
第一次启动大概率服Yggdrasil服务器收不到任何请求

### ISSUE THREAD

**Issue by rinscr3003** [yushijinhun/authlib-injector#50]
你好，我现在使用authlib-injector开发了Makku启动器，目前遇到以下情况：
1 首次启动大概率提示验证服务正在停机维护，Yggdrasil服务器日志没提示收到请求
2 玩家因网络异常掉线后无法重连，会提示各种千奇百怪的错误，服务器控制台则是Netty的报错提示
如果需要详细日志，我可稍后上传，望解答。

**Comment by xfl03** [comment]
需要详细日志，谢谢

**Comment by rinscr3003** [comment]
刚刚检查了一下发现几乎没有任何日志，Yggdrasil的服务器没有任何日志（Django runserver），Spigot只有一句player disconnect，本地的mc客户端则是日志显示开始连接20s后显示stop，用户看到界面显示验证服务正在停机维护。
至于错误二，今天晚上我会在建筑组遇到故障时立即上传日志

**Comment by xfl03** [comment]
无法重现这个bug，还是需要日志来进行判断，麻烦了

**Comment by rinscr3003** [comment]
第一个故障经过不断调整网络参数得到优化，出现频率下降，只是偶尔会提示了
第二个故障一旦发生只能重启服务器和认证服务器才可修复，但是认证服务器上访问日志与正常认证没有任何区别，netty的错误信息遇到后贴上来

**Comment by xfl03** [comment]
长时间未提供有效信息，请提供后重新打开
