### ISSUE TITLE
在获取皮肤的特定情况下会NPE

### ISSUE THREAD

**Issue by sandtechnology** [yushijinhun/authlib-injector#51]
详见http://www.mcbbs.net/thread-882040-1-1.html
Crashreport：https://paste.ubuntu.com/p/BnKpGHKHrz/

**Comment by xfl03** [comment]
我看了Mojang的源代码，也没有对url为null的情况进行考虑，他们从源头上杜绝了null的可能性，我怀疑是用户所使用的后端返回了不符合Yggdrasil服务端技术规范的内容。
