### ISSUE TITLE
1.14.3用不了...

### ISSUE THREAD

**Issue by cnluminous** [yushijinhun/authlib-injector#52]
1.14.3用不了....放进去后报错然后就不载入啊.

**Comment by zhzRedstone** [comment]
无日志言卵。。。(请提供客户端和启动器日志。。)

**Comment by cnluminous** [comment]
e这不是插件么

**Comment by cnluminous** [comment]
> [09:48:42 ERROR]: Could not load 'plugins/authlib-injector-1.1.26-41a7a47.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:159) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:141) ~[patched_1.14.3.jar:git-Paper-123]
at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:354) ~[patched_1.14.3.jar:git-Paper-123]
at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:218) ~[patched_1.14.3.jar:git-Paper-123]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:859) ~[patched_1.14.3.jar:git-Paper-123]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
... 6 more

**Comment by cnluminous** [comment]
客户端hmcl

**Comment by xfl03** [comment]
> Could not load 'plugins/authlib-injector-1.1.26-41a7a47.jar' in folder 'plugins'

这不是插件啊……………………………………

**Comment by zhzRedstone** [comment]
Could not load 'plugins/authlib-injector-1.1.26-41a7a47.jar' in folder 'plugins'
很明显这不是插件、、
用法：在服务器启动脚本加参数，
比如
```
java -Xms512M -Xmx1024M -javaagent:authlib-injector的文件路径/authlib-injector-*******.jar=yggdrasil apiroot -jar spigot.jar
```

**Comment by zhzRedstone** [comment]
> 客户端hmcl

你管HMCL叫客户端。。
HMCL不是启动器吗？

**Comment by LazyCreeper** [comment]
1.14.3显示服务器宕机
启动参数如下：
`java -javaagent:authlib-injector-1.1.26-41a7a47.jar=https://skin.cancer360.top/api/yggdrasil -XX:+UseG1GC -XX:+AggressiveOpts -XX:+UseCompressedOops -Dfml.queryResult=confirm -Xmx10G -Xms10G -jar Paper-1.14.3-f749422-20190630-0410.jar`
服务器日志如下：
`[ authlib-injector.launch ] [ INFO ] Version: 1.1.26-41a7a47
[ authlib-injector.config ] [ INFO ] API root: https://skin.cancer360.top/api/yggdrasil/
*** Warning, you've not updated in a while! ***
*** Please download a new build as per instructions from https://papermc.io/downloads ***
System Info: Java 1.8 (OpenJDK 64-Bit Server VM 25.212-b04) Host:  Linux 3.10.0-957.el7.x86_64 (amd64)
Loading libraries, please wait...
2019-07-22  08:58:59 ,243 main WARN Disabling terminal, you're running in an unsupported environment.
[ authlib-injector.httpd ] [ INFO ] Httpd is running on port 37054
[ authlib-injector.transform ] [ INFO ] Transformed [ com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService ] with [ Constant URL Transformer ]
[ authlib-injector.transform ] [ INFO ] Transformed [ com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService ] with [ Texture Whitelist Transformer ]
[ authlib-injector.transform ] [ INFO ] Transformed [ com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService ] with [ Yggdrasil Public Key Transformer ]
[ authlib-injector.transform ] [ INFO ] Transformed [ com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository ] with [ Constant URL Transformer ]
[  08:59:06  INFO ]: Starting minecraft server version 1.14.3`
然而进入游戏时提示：验证服务器宕机，请稍后重试

**Comment by xfl03** [comment]
@LazyCreeper 
请提供客户端日志
