### ISSUE TITLE
服务器启动后直接提示http403错误  浏览器可以访问

### ISSUE THREAD

**Issue by WindyMadman** [yushijinhun/authlib-injector#54]
这是日志

`[authlib-injector.launch] [INFO] Version: 1.1.26-41a7a47
[authlib-injector.config] [INFO] API root: https://bss.fengzi.run/api/yggdrasil/
[authlib-injector.config] [SEVERE] Failed to fetch metadata: java.io.IOException: Server returned HTTP response code: 403 for URL: https://bss.fengzi.run/api/yggdrasil/`

**Comment by 2810676203** [comment]
启动器使用也没任何问题这个问题只在服务端出现

**Comment by xfl03** [comment]
API网页服务端可能对UA进行了检测，请自行关闭

**Comment by GiriNeko** [comment]
我使用的是Blessing Skin Server，我遇到了和你同样的问题。
若您启用了cloudflare，可以尝试关闭位于 Firewall > Web Application Firewall > Browser Integrity Check 的选项
原帖[在这里](https://github.com/bs-community/yggdrasil-api/wiki/0x04-%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF-Troubleshooting)
