### ISSUE TITLE
[proposal] 允许正版登录用户进入服务器

### ISSUE THREAD

**Issue by way-zer** [yushijinhun/authlib-injector#56]
外置登录导致正版用户不能自由的进入所有服务器，必须退出切换外置(非正版)登录。
**建议应该保证正版用户的权益**
## 实现方式
在`GET /sessionserver/session/minecraft/hasJoined?username={username}&serverId={serverId}&ip={ip}`实现部分，向上转发请求(mojang服务器)，验证玩家是否正版登录
### 保存信息
在玩家正版验证成功后，为玩家建立一个外置登录账号(密码:待定,uuid为正版UUID),防止其他玩家盗注或者登录，也为正版用户往后使用外置登录提供基础
### 遭遇已有外置登录账号
正版登录获取的uuid不可能(99.9%)与以往非正版uuid一样，对于使用uuid的插件，可以视为两个用户.
你也可以按照服务器不同情况，设置其他方案
**注意**: 前面的保存信息会产生一个uuid相同的账号,此账号可给与标注
### 预防攻击
向上转发时，可以设定单位时间连接数量，超出时，可以放弃正版验证
### 已知问题
正版客户端会不信任盗版用户的皮肤站

**Comment by way-zer** [comment]
向上转发时，可以设定单位时间连接数量，超出时，可以放弃正版验证

**Comment by xfl03** [comment]
之前考虑过这个问题，正版登录的用户会看不到其他没有使用正版登录用户的皮肤，因此暂时没有这样做。
不过，这个需求如果要实现的话，应该也是ygg服务端实现的，authlib-injector似乎不需要为此进行修改？

**Comment by way-zer** [comment]
这个是和authlib-injector没啥关系，但是这个仓库不是还有ygg服务端规范吗，要提只能在这呢。
皮肤是次要的吧，至少能保证进入服务器，而且正版皮肤应该能看得到

**Comment by xfl03** [comment]
ygg服务端可以实现此功能，不适合写入规范
