### ISSUE TITLE
在部分电脑中，HMCL使用authlib-injector无法启动游戏，无法确定原因。

### ISSUE THREAD

**Issue by GouLiGuoJiaNaive** [yushijinhun/authlib-injector#59]
org.jackhuang.hmcl.auth.authlibinjector.AuthlibInjectorDownloadException: java.io.IOException: Malformed response
![image](https://user-images.githubusercontent.com/30216016/72131610-bfe97000-33b7-11ea-8148-581dd2aa1d2e.png)

**Comment by hempflower** [comment]
这应该是HMCL的错误，看起来与authlib-injector的下载有关。建议移步至:https://github.com/huanghongxun/HMCL
