### ISSUE TITLE
关于文档中角色信息部分的问题

### ISSUE THREAD

**Issue by ChenHauShen** [yushijinhun/authlib-injector#71]
[https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E8%A7%92%E8%89%B2profile](url)
此处材质模型是否由原来的
```
可选值：STEVE、ALEX
```
修改为:
```
可选值：STEVE、slim
```
官方API调用获取的用户信息显示为slim
```
{
  "timestamp" : 1591703610606,
  "profileId" : "13e****************404",
  "profileName" : "*******",
  "textures" : {
    "SKIN" : {
      "url" : "http://textures.minecraft.net/texture/9c3c4cf635d24ff8e3fa08c1f99956b0716d9b8b68db39975abcd7531c2c845b",
      "metadata" : {
        "model" : "slim"
      }
    }
  }
}
```

**Comment by yushijinhun** [comment]
> 材质元数据中目前已知的键有 model。 model 只出现在 SKIN 材质中，用于表示该角色的模型。它的值可以为 default 或 slim ，其中 default 代表 STEVE，slim 代表 ALEX。

wiki 内容并没有错误，但可能有些误导。我会改变一下表述。
