### ISSUE TITLE
1.13+ SkullOwner NBT 中 @mojang 后缀不生效

### ISSUE THREAD

**Issue by NPBeta** [yushijinhun/authlib-injector#76]
如题，1.13+ 对物品进行了扁平化，即原有 minecraft:skull 3 变更为 minecraft:player_head，因此命令对应变更为 `/give @s minecraft:player_head{SkullOwner:"<玩家名>"}`. 不知道是否是此原因，导致 `@mojang` 后缀不生效，获得的头颅名称为 "xxx@mojang 的头"，并且材质也不正确。
![image](https://user-images.githubusercontent.com/17808640/89094865-35bc3400-d3fb-11ea-8039-878da0293f69.png)
![image](https://user-images.githubusercontent.com/17808640/89094868-3d7bd880-d3fb-11ea-8df1-f7ffc564f5ee.png)
![image](https://user-images.githubusercontent.com/17808640/89094870-45d41380-d3fb-11ea-8bac-ab5bf94ca830.png)

**Comment by yushijinhun** [comment]
I cannot reproduce your problem.

![image](https://user-images.githubusercontent.com/8373027/89103271-295bc980-d443-11ea-9bda-5f6593e44f27.png)

Could you please enable debug logging by adding `-Dauthlibinjector.debug=all` parameter to JVM arguments and provide console logs?

**Comment by NPBeta** [comment]
> enable debug logging by adding `-Dauthlibinjector.debug=all` parameter to JVM arguments

Where should I enable debug logging? I mean, server or client? I'm the server's owner, too.
I would like to try it on client first. The log will be posted later.

**Comment by NPBeta** [comment]
Sorry I didn't clearify my game version.
Server: Paper-1.16.1
Client: HMCL 3.2.172 / Vanilla 1.16.1 / Optifine HD U G2 pre5
Authlib-Injector: 1.1.29

**Comment by NPBeta** [comment]
![image](https://user-images.githubusercontent.com/17808640/89103770-ee5b9500-d446-11ea-9d1c-c79af7899545.png)

I've trimmed the log to avoid useless info like Optifine logs.

> [authlib-injector.launch] [INFO] Version: 1.1.29
[authlib-injector.launch] [FINE] Detected side: CLIENT
[authlib-injector.config] [INFO] API root: https://my.skin.site/api/yggdrasil/
[authlib-injector.config] [INFO] Prefetched metadata detected
[authlib-injector.config] [FINE] Metadata: {"meta":{"serverName":"BlessingSkin","implementationName":"Yggdrasil API for Blessing Skin","implementationVersion":"4.8.2","links":{"homepage":"https:\/\/my.skin.site","register":"https:\/\/my.skin.site\/auth\/register"}},"skinDomains":["my.skin.site"],"signaturePublickey":"-----BEGIN PUBLIC KEY-----\nMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxxWnc6duSRNwrExZKYAk\nd1XUQ3QrZOPjd\/pAEjBOtO8wql0Px1nVertWA9NhlwiAE4yK0PNPHy+Yif41LyiW\nFp3ncvx9XGBpGC2TTtsa8q2KrmiRnl4HCh7626wRBWhdtOeQPKYm3I6Hd0Bll041\nn3dPfRV3YC69S+WayUYDbVMkSjYVIjfoDKm11EYxA5i5HYjtR3Kj04fk0AP0D7+M\nWGrSKLDwSdT3sNmT\/1UM7wRzVpw4xqvSdWJxItD78Px0ID1H+vqR+0EJHJCp2VOY\ndCl\/mjUAuXQ9PZC+2Jbtfi0XATQ7ploKvWhihQny+mTW\/+BX0kOqri7mxq88s7dT\njmbJndd\/Tk+x\/CrXrJ8aSgTUL+NR\/UNRPzMnXga6LJVH0SQpqK8AvvA8muUzz7NN\nHy5Yog1VhoCuSNY+SuvhlRGfKgOGF5uMlEJf8Lct4NNN1jWpvPspjeX59d1MBiZU\n5CJL\/8S+QaLajlms9LfBqwkF1W4TMA0Qf6lVSjGo2q7GLhemeWhNensi\/NAx5EHi\n2eErA1QglOKYGS56+S6fx8wCfRbpfH+p6esEm7Q\/iCjpAwNWphUMUIiqZeRa47Cw\nHYp3DEey0b1y6Bbfcmr\/90H3cSLyOI+0TeAg1agbuc\/OAAn6lRpXBHIMCKGHWqq2\n\/2lzkbIm0dHD9z+n5ZtOcKECAwEAAQ==\n-----END PUBLIC KEY-----\n"}
[authlib-injector.config] [FINE] Parsed metadata: YggdrasilConfiguration [apiRoot=https://my.skin.site/api/yggdrasil/, skinDomains=[my.skin.site], decodedPublickey=Optional[Sun RSA public key, 4096 bits
  params: null
  modulus: 812194251783079905889257249866892825136865390683640502002298080747366618832396907090756564320859000027513813781392334477722522808268203526435595605525190255155398675476156554802402109183273518985500610658932706281685020662504673358997045198896468488747922704741657025026527845012391676294390440303547844978252652135570319749169145284180313710210045994326202741435222462320739094671434559524466812228591389205176893284878543523827287614397796225380846951456457997607576063677112886139656907791406591928199882728723307828267625481749578663244073848262440690392415798598721702226479605776879201218529827146569592654402215353036421180661435345512977222259845242791752844230245238265984591592288267214290798423189535273383587423571738212593165396485065779268939456073415353736716258012118632355811593446522770183652420195483307326053988023560440321844123590980065311862304969845904961211795922464822921943010249602903824730245463367770950446754234324356840186927893603704700542876083143882903660599683417427970162447376969923581667509600571704629641376343898355537299504070199654621311735486739338967976942659232327513247324509863378383880736309606569551415173949048271498848121981627759604759392989332372294855328846220378032908568260769
  public exponent: 65537], meta={implementationName=Yggdrasil API for Blessing Skin, implementationVersion=4.8.2, links={"homepage":"https:\/\/my.skin.site","register":"https:\/\/my.skin.site\/auth\/register"}, serverName=BlessingSkin}]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.legacy.LegacyMinecraftSessionService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.legacy.LegacyMinecraftSessionService] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.legacy.LegacyUserAuthentication] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.legacy.LegacyUserAuthentication] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.BaseUserAuthentication] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.BaseUserAuthentication] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Authlib Log Interceptor]
[authlib-injector.transform] [FINE] Transformed url [https://authserver.mojang.com] to [https://my.skin.site/api/yggdrasil/authserver]
[authlib-injector.transform] [FINE] Transformed url [https://api.mojang.com] to [https://my.skin.site/api/yggdrasil/api]
[authlib-injector.transform] [FINE] Transformed url [https://sessionserver.mojang.com] to [https://my.skin.site/api/yggdrasil/sessionserver]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilUserAuthentication] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Yggdrasil Public Key Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.Agent] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.Agent] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.EnvironmentParser] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.EnvironmentParser] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture$Type] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture$Type] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.UserType] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.UserType] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [net.minecraft.client.main.Main] with [Main Arguments Transformer]
[authlib-injector.transform] [INFO] Transformed [net.minecraft.client.main.Main] with [Callback Metafactory Transformer]
[authlib-injector.transform] [FINE] Main arguments: --username <player> --assetIndex 1.16 --uuid <uuid> --accessToken <access token> --userType mojang --versionType HMCL 3.3.173 --width 854 --height 480 --gameDir E:\GamesLibrary\Minecraft\1.16.1\.minecraft --assetsDir E:\GamesLibrary\Minecraft\1.16.1\.minecraft\assets --version HMCL 3.3.173
[authlib-injector.transform] [FINE] Version series detected: 1.16
[authlib-injector.httpd] [INFO] Httpd is running on port 3482
[authlib-injector.transform] [FINE] Transformed url [http://skins.minecraft.net/MinecraftSkins/%s.png] to [http://127.0.0.1:3482/http/skins.minecraft.net/MinecraftSkins/%s.png]
[authlib-injector.transform] [INFO] Transformed [ebc] with [Constant URL Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.HttpAuthenticationService] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Registered log handler on sun.misc.Launcher$AppClassLoader@18b4aac2
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.EnvironmentParser] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.EnvironmentParser] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Authlib Log Interceptor]
[authlib-injector.transform] [FINE] Transformed url [https://authserver.mojang.com] to [https://my.skin.site/api/yggdrasil/authserver]
[authlib-injector.transform] [FINE] Transformed url [https://api.mojang.com] to [https://my.skin.site/api/yggdrasil/api]
[authlib-injector.transform] [FINE] Transformed url [https://sessionserver.mojang.com] to [https://my.skin.site/api/yggdrasil/sessionserver]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Constant URL Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilEnvironment] with [Callback Metafactory Transformer]
[22:23:11] [main/INFO]: Environment: authHost='https://my.skin.site/api/yggdrasil/authserver', accountsHost='https://my.skin.site/api/yggdrasil/api', sessionHost='https://my.skin.site/api/yggdrasil/sessionserver', name='PROD'
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Texture Whitelist Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Yggdrasil Public Key Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService] with [Callback Metafactory Transformer]
[22:23:52] [main/INFO]: Connecting to my.game.server., 25565
[22:23:55] [main/INFO]: Environment: authHost='https://my.skin.site/api/yggdrasil/authserver', accountsHost='https://my.skin.site/api/yggdrasil/api', sessionHost='https://my.skin.site/api/yggdrasil/sessionserver', name='PROD'
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.yggdrasil.YggdrasilGameProfileRepository] with [Callback Metafactory Transformer]
[22:23:55] [main/WARN]: Unknown custom packed identifier: minecraft:register
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture$Type] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture$Type] with [Callback Metafactory Transformer]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture] with [Authlib Log Interceptor]
[authlib-injector.transform] [INFO] Transformed [com.mojang.authlib.minecraft.MinecraftProfileTexture] with [Callback Metafactory Transformer]
[22:24:10] [main/INFO]: [CHAT] 已设置<player>的游戏模式为创造模式.
[22:24:51] [main/INFO]: [CHAT] 已将1个[notch的头]给予<player>
[22:24:56] [main/INFO]: [CHAT] 已将1个[notch@mojang的头]给予<player>

**Comment by NPBeta** [comment]
UPDATE:
Tried disable OptiFine - doesn't work.
Tried get a existing player's skull - all works fine.
Tried on a Singleplayer world - doesn't work.

**Comment by yushijinhun** [comment]
I have successfully reproduced your problem on vanila minecraft 1.16.1 (no optifine, singleplayer). But it works fine on vanila minecraft 1.13.2 (no optifine, singleplayer).

I will look into this problem.

Btw, did you encounter any crash after placing `notch@mojang`'s skull?

**Comment by NPBeta** [comment]
> But it works fine on vanila minecraft 1.13.2 (no optifine, singleplayer).

It doesn't work for me on 1.13.2. But if you cannot reproduce it, seems this bug doesn't affect 1.13.2.
Need more test on 1.14.x and 1.15.x. (I will test it when I'm free).



> Btw, did you encounter any crash after placing `notch@mojang`'s skull?

No. No warnings, error or fetal have been outputted to Log.

**Comment by yushijinhun** [comment]
The bug first occurs in authlib 1.6.25 (or Minecraft 1.16), so it should work fine if you're using 1.13.2.

To test the fix, you can download the snapshot build from [GitHub Actions](https://github.com/yushijinhun/authlib-injector/actions/runs/198928193) (it's 'artifact' file in Artifacts section), and tell HMCL to use it by appending `-Dhmcl.authlibinjector.location=/path/to/authlib-injector.jar` to **HMCL's commandline**.

Please check if this fixes your problem. Thanks.

p.s. I'm speaking English because I can't get Chinese IME to work on my Ubuntu laptop.

**Comment by NPBeta** [comment]
> Please check if this fixes your problem. Thanks.

Confirm Fixed.
