### ISSUE TITLE
请兼容 Geyser 服务端或插件

### ISSUE THREAD

**Issue by MlgmXyysd** [yushijinhun/authlib-injector#83]
如题，1.16.2 时基岩版使用 Geyser 服务端或插件作为转发连接 Java 服务器时会出现 `Authentication servers are down. Please try again later, sorry!` 问题，更多详细信息请参阅 https://github.com/GeyserMC/Geyser/issues/1178

Geyser 方是这么解释的：
https://github.com/GeyserMC/Geyser/issues/1095#issuecomment-675202620

Ref: [Geyser](https://github.com/GeyserMC/Geyser/)

**Comment by yushijinhun** [comment]
standalone Geyser + vanilla 1.16.2: ok
standalone Geyser + spigot 1.16.2: ok
spigot 1.16.2 + Geyser plugin: **reproduced**
