### ISSUE TITLE
[proposal] 支持邮箱以外的登录方式

### ISSUE THREAD

**Issue by yushijinhun** [yushijinhun/authlib-injector#85]
## 概述
目前 authlib-injector 只支持邮箱登录一种登录方式，这是沿袭了 Mojang 要求使用邮箱登录的传统。本提案旨在于允许用户使用邮箱之外的凭证进行登录，例如使用角色名登录。

这一功能需要验证服务器和启动器的支持。

#### feature.non_email_login 选项
验证服务器需要在元数据中增加一个 `feature.non_email_login` 字段（[位于 `meta` 下](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#meta-%E4%B8%AD%E7%9A%84%E5%85%83%E6%95%B0%E6%8D%AE)），用来指示验证服务器是否接受除邮箱之外的登录方式。`feature.non_email_login` 是一个布尔类型的字段，默认值为 false（即只支持邮箱登录）。

#### 登录接口
如果验证服务器接受除邮箱之外的登录方式，那么登录接口（[`POST /authserver/authenticate`](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E7%99%BB%E5%BD%95)）请求中的 `username` 字段就不再只能是邮箱了，而可以是任意字符串。

### 启动器
如果验证服务器返回的元数据中 `feature.non_email_login` 字段为 true，就代表服务器支持使用除邮箱外的凭证登录。此时，启动器需要注意以下几点：
 * 登录界面中，应采用「账户」作为字段名称，而非「邮箱」，以免造成迷惑。
    * 如果启动器原先就使用「账户」之类措辞则无须担心。
 * **不需要**检查用户输入的账户是否是合法的邮箱格式。
   * 如果启动器原先就不检查输入格式，也无须担心。

## 关于使用角色名登录
这一功能的最大应用场景是**使用角色名登录**，也就是登录时输入角色名称而非邮箱。当用户使用角色名称登录时，验证服务器应**自动选中相应角色**，即[登录接口](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E7%99%BB%E5%BD%95)响应中的 `selectedProfile` 应为用户登录时所使用的角色。这种情况下，如果用户存在多个角色，那么他可以省去[选择角色](https://github.com/yushijinhun/authlib-injector/wiki/Yggdrasil-%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%8A%80%E6%9C%AF%E8%A7%84%E8%8C%83#%E5%88%B7%E6%96%B0)的操作。

某些程序不支持多角色（例如 Geyser），则可以通过上述方法绕过选择角色。

------
/cc @mochaaP @g-plane @huanghongxun @TT702 @Nsiso @LTCatt

**Comment by g-plane** [comment]
`availableProfiles` 是不是不需要改变？

**Comment by yushijinhun** [comment]
> `availableProfiles` 是不是不需要改变？

不需要

**Comment by yushijinhun** [comment]
wiki 已更新：[bf66432e7773fe6ce3633e8d0527f53c490fbcd0](https://github.com/yushijinhun/authlib-injector/wiki/_compare/6ba582d0e06dff69dc918d38f48b58de93111b18...bf66432e7773fe6ce3633e8d0527f53c490fbcd0)
