### ISSUE TITLE
无法连接到验证API

### ISSUE THREAD

**Issue by ddaodan** [yushijinhun/authlib-injector#88]
服务端的网络无法直接连接到验证API（提示timeout）因此使用了代理
但是开服的时候报错：
```
[authlib-injector.launch] [INFO] Version: 1.1.30 
[authlib-injector.config] [INFO] API root: https://skin.ddaodan.club/api/yggdrasil 
[authlib-injector.config] [SEVERE] Failed to fetch metadata: java.net.ConnectException: Connection timed out: connect
```
可以确定是因为上面所说的原因造成的，但是不知道该如何解决

**Comment by hempflower** [comment]
贴一下启动命令行

**Comment by ddaodan** [comment]
已删减无关内容

```
@ECHO OFF
@echo. 服务器正在启动中,请稍等……
java -javaagent:authlib-injector-1.1.30.jar=https://skin.ddaodan.club/api/yggdrasil -Xms1024M -Xmx1024M -jar paperclip.jar
pause
EXIT
```

**Comment by hempflower** [comment]
请阅读: https://github.com/yushijinhun/authlib-injector#%E5%8F%82%E6%95%B0

**Comment by hempflower** [comment]
若要通过代理访问ygg服务器，应该在**启动参数中指定代理服务器地址**。authlib-injector 不会自动使用系统代理。

**Comment by ddaodan** [comment]
> 请阅读: https://github.com/yushijinhun/authlib-injector#%E5%8F%82%E6%95%B0

目前还无法直接使用浏览器代理吗？

**Comment by hempflower** [comment]
> -Dauthlibinjector.mojangProxy={代理服务器 URL}
    设置访问 Mojang 验证服务时使用的代理, 目前仅支持 **SOCKS** 协议.
    URL 格式: socks://\<host>:\<port>

**Comment by ddaodan** [comment]
> 若要通过代理访问ygg服务器，应该在**启动参数中指定代理服务器地址**。authlib-injector 不会自动使用系统代理。

好的，我试试看（能用系统代理就更好了）

**Comment by yushijinhun** [comment]
@ddaodan 如要设置代理，可以使用以下参数：
* HTTP 代理：`-Dhttp.proxyHost=example.com` `-Dhttp.proxyPort=8080`
* SOCKS 代理：`-DsocksProxyHost=example.com` `-DsocksProxyPort=2080`

参考： https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

----
@hempflower 你所提到的 `-Dauthlibinjector.mojangProxy` 并不适合此场景，请仔细阅读文档，以及此 issue 的问题。另外，请不要在短时间内刷大量的 comments。
