### ISSUE TITLE
authlib-injector 的url地址的服务器不可以使用cdn吗？

### ISSUE THREAD

**Issue by luluxiaoyu** [yushijinhun/authlib-injector#89]
authlib-injector 的url地址的服务器不可以使用cdn吗？
用了cdn好像启动不了

**Comment by yushijinhun** [comment]
> 用了cdn好像启动不了

请提供具体的错误信息。

**Comment by luluxiaoyu** [comment]
> > 用了cdn好像启动不了
> 
> 请提供具体的错误信息。


auth1 ib-in jector] [ INFO ] Version:

1.1.33

authlib-in jector] [ ERROR] No authentication server speci fiedMC SMANAGER ]

**Comment by yushijinhun** [comment]
你这个应该是参数填写有问题。
