### ISSUE TITLE
启动服务器报错

### ISSUE THREAD

**Issue by Timolop233** [yushijinhun/authlib-injector#93]
在我启动服务器的时候authlib-injector报错[ERROR] Failed to fetch metadata: java.net.SocketException: Unexpected end of file from server

**Comment by yushijinhun** [comment]
抱歉回复的有点晚，因为最近比较忙。

这应该是你验证服务器的问题，请贴出完整的 java 命令行。

**Comment by abbiezhu** [comment]
目录: AllofFabric3Server-2.4.1


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----       2020/11/16      9:21                .fabric                                                               
d-----       2020/11/16      9:21                .mixin.out                                                            
d-----       2020/11/17     10:32                config                                                                
d-----       2020/11/17     10:32                kubejs                                                                
d-----       2020/11/17     10:35                logs                                                                  
d-----       2020/11/17     10:34                mods                                                                  
d-----       2020/11/17     10:32                OLD_TO_DELETE                                                         
d-----       2020/11/16      9:21                patchouli_books                                                       
d-----       2020/11/16      9:26                rrp.debug                                                             
d-----       2020/11/17     10:35                world                                                                 
-a----       2020/11/17     10:38              0 aaaa.txt                                                              
-a----       2020/11/16     10:58         305251 authlib-injector-1.1.34.jar                                           
-a----       2020/11/17     10:35              2 banned-ips.json                                                       
-a----       2020/11/17     10:35              2 banned-players.json                                                   
-a----       2020/11/16      9:26            183 eula.txt                                                              
-a----       2020/11/17     10:34        5169435 fabric-server-launch.jar                                              
-a----       2020/11/16      9:21             53 fabric-server-launcher.properties                                     
-a----       2020/11/17     10:32          13831 manifest.json                                                         
-a----       2020/11/17     10:32        2447076 modpack-download.zip                                                  
-a----       2020/11/17     10:35              2 ops.json                                                              
-a----       2020/11/16      9:13            560 options.txt                                                           
-a----       2020/11/13     13:11           8164 server-icon.png                                                       
-a----       2020/11/13     15:45           5694 server-setup-config.yaml                                              
-a----       2020/11/17     10:35       37942656 server.jar                                                            
-a----       2020/11/17     10:35           1112 server.properties                                                     
-a----       2020/11/17     10:32          18285 servers.dat                                                           
-a----        2020/2/29      0:49        2710446 serverstarter-2.0.1.jar                                               
-a----       2020/11/17     10:35            243 serverstarter.lock                                                    
-a----       2020/11/16      9:20            243 serverstarter.lock.aaaaaaaaaaaaaaaaaa                                 
-a----       2020/11/16      9:42            243 serverstarter.lock。111111111                                          
------       2020/11/17     10:32              0 serverstarter.log                                                     
-a----       2020/11/16     11:43            867 startserver.bat                                                       
-a----       2020/10/17      4:56           1405 startserver.sh                                                        
-a----       2020/11/17     10:35            102 usercache.json                                                        
-a----       2020/11/16      9:26              2 whitelist.json                                                        
、
这是我服务端的目录结构，里面 的startserver.bat内容如下：
@ECHO OFF
SETLOCAL


:BEGIN
CLS
COLOR 3F >nul 2>&1
SET MC_SYS32=%SYSTEMROOT%\SYSTEM32
REM Make batch directory the same as the directory it's being called from
REM For example, if "run as admin" the batch starting dir could be system32
CD "%~dp0" >nul 2>&1

:CHECK
REM Check if serverstarter JAR is already downloaded
IF NOT EXIST "%cd%\serverstarter-2.0.1.jar" (
	ECHO serverstarter binary not found, downloading serverstarter...
	%SYSTEMROOT%\SYSTEM32\bitsadmin.exe /rawreturn /nowrap /transfer starter /dynamic /download /priority foreground https://github.com/Yoosk/ServerStarter/releases/download/v2.0.1/serverstarter-2.0.1.jar "%cd%\serverstarter-2.0.1.jar"
   GOTO MAIN
) ELSE (
   GOTO MAIN
)

:MAIN
java -javaagent:authlib-injector-1.1.34.jar=http://skin.lymiss.com/api/yggdrasil  -jar serverstarter-2.0.1.jar 
GOTO EOF

:EOF
pause

现在是 只能离线 皮肤可以用，账号无法验证。这个目录 里面有3个JAR

fabric-server-launch.jar、server.jar、serverstarter-2.0.1.jar

帮助手册里面 的方法，我修改成这样
java -javaagent:authlib-injector-1.1.34.jar=http://skin.lymiss.com/api/yggdrasil  -jar serverstarter-2.0.1.jar 
如果 server.properties设为：
online-mode=true
是登陆不了游戏的。

**Comment by abbiezhu** [comment]
[10:54:57] [User Authenticator #1/INFO]: Disconnecting /127.0.0.1:61814: Failed to verify username!
[10:54:57] [User Authenticator #1/ERROR]: Username 'ABB' tried to join with an invalid session
[10:54:57] [Server thread/INFO]: /127.0.0.1:61814 lost connection: Failed to verify username!

**Comment by yushijinhun** [comment]
@abbiezhu 请检查下 MC 客户端用的验证服务器和 MC 服务端用的是不是同一个。如果 MC 客户端登录的是正版，或者其他验证服务器，那么在进服的时候就会出现 `Failed to verify username!` 错误。

此外，反馈问题时请新开一个 issue，不要在已有 issue 下提无关的问题。

**Comment by yushijinhun** [comment]
@Timolop233 你的问题解决了吗？

**Comment by yushijinhun** [comment]
由于长时间未回复，此 issue 关闭。
