### ISSUE TITLE
验证无法通过

### ISSUE THREAD

**Issue by abbiezhu** [yushijinhun/authlib-injector#94]
我按你给我说的，检查了服务端的  startsever.bat:
-----------------------------------------------------------------------------------
@ECHO OFF
SETLOCAL

:BEGIN
CLS
COLOR 3F >nul 2>&1
SET MC_SYS32=%SYSTEMROOT%\SYSTEM32
REM Make batch directory the same as the directory it's being called from
REM For example, if "run as admin" the batch starting dir could be system32
CD "%~dp0" >nul 2>&1

:CHECK
REM Check if serverstarter JAR is already downloaded
IF NOT EXIST "%cd%\serverstarter-2.0.1.jar" (
	ECHO serverstarter binary not found, downloading serverstarter...
	%SYSTEMROOT%\SYSTEM32\bitsadmin.exe /rawreturn /nowrap /transfer starter /dynamic /download /priority foreground https://github.com/Yoosk/ServerStarter/releases/download/v2.0.1/serverstarter-2.0.1.jar "%cd%\serverstarter-2.0.1.jar"
   GOTO MAIN
) ELSE (
   GOTO MAIN
)

:MAIN
java -javaagent:authlib-injector-1.1.34.jar=http://skin.lymiss.com/api/yggdrasil  -jar serverstarter-2.0.1.jar 
GOTO EOF

:EOF
pause
-----------------------------------------------------------------------------------
客户端 ：
登陆方式：外置登陆（anthlib-injector）
认证服务器：http://skin.lymiss.com/api/yggdrasil （确认相同）

账号、密码 可以登陆。
游戏启动后， 在多人游戏列表 ，
当server.properties 文件设为：
online-mode=true
进入游戏时提示：
Failed to verify username!
设为false 能进游戏，且皮肤可用。

如果是官网的的 server.jar的话 因为只有一个JAR 文件 ，用手册的方法：
-javaagent:{authlib-injector.jar 的路径}={验证服务器 URL (API 地址)}
是没有问题的。

就是现在国外新的整合包都是这种 ，里面有3个JAR ：
fabric-server-launch.jar、server.jar、serverstarter-2.0.1.jar
上面说的服务端的  startsever.bat文件内容改成这样 服务是可以启动的，但结果是一样不能验证账号:
java   -jar serverstarter-2.0.1.jar  -javaagent:authlib-injector-1.1.34.jar=http://skin.lymiss.com/api/yggdrasil

**Comment by yushijinhun** [comment]
把命令行中的 `serverstarter-2.0.1.jar` 换成 `fabric-server-launch.jar` 行不行呢？

**Comment by yushijinhun** [comment]
顺便一说，`-javaagent` 参数是一定要放在 `-jar` 前的。

**Comment by abbiezhu** [comment]
> 
> 
> 把命令行中的 `serverstarter-2.0.1.jar` 换成 `fabric-server-launch.jar` 行不行呢？
没想到能得到你 及时的回复~验证通过了！！感谢！感谢！
