### ISSUE TITLE
[问题反馈]在服务端部署后一段时间后出现无法验证的问题

### ISSUE THREAD

**Issue by Small-Miao** [yushijinhun/authlib-injector#95]
信息
服务器版本为 catserver 999edd9b 1.12.2
服务器系统 windows 2019 server
内存 16G 
CPU E5645

客户端启动器为 HMCL 3.2.0.0
服务器使用版本为 authlib-injector 1.1.34

主要报错为
[Server thread/ERROR]: HandshakeMessageHandler exception
java.lang.VerifyError: Bad type on operand stack
然后无法验证 并连接超时.

服务器验证仅在上午正常 下午无法验证并报错
[latest.log](https://github.com/yushijinhun/authlib-injector/files/5601229/latest.log)

**Comment by yushijinhun** [comment]
请问问题解决了吗？
