### ISSUE TITLE
我用blessskin作为验证服务器，一旦使用cloudflare cdn客户端就无法登录

### ISSUE THREAD

**Issue by luluxiaoyu** [yushijinhun/authlib-injector#98]
我用blessskin作为验证服务器，一旦使用cloudflare cdn客户端就无法登录
显示：登录验证服务器停机维护
cloudflare cdn防火墙已关闭

**Comment by yushijinhun** [comment]
请在启动器的 JVM 参数中添加 `-Dauthlibinjector.debug`，然后上传控制台输出，其中应该会包含详细的错误信息。

**Comment by yushijinhun** [comment]
根据其他用户的反馈，你可以尝试一下关闭 Cloudflare 的 Browser Integrity Check（位于 Firewall/Settings 下）。

**Comment by luluxiaoyu** [comment]
好的 我尝试一下

**Comment by luluxiaoyu** [comment]
可以了 谢谢！
